"""Regenerate the sample stories in ``ai/examples/``.

    python3 scripts/generate_examples.py          # run from the ai/ folder

Every file in ``ai/examples/`` is produced by this script from the reviewed
content in ``content/ai-ready/`` - none of it is written by hand. Re-run it
whenever the content summaries or the generator change, and commit the result,
so the examples always reflect what the module actually returns.

With no ANTHROPIC_API_KEY set, the offline extractive backend produces the
output, which makes the examples deterministic and reviewable in a diff.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from service import audiences, llm  # noqa: E402
from service.generator import answer_question, generate_story  # noqa: E402
from service.models import GuideRequest, StoryRequest  # noqa: E402

AI_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXAMPLES_DIR = os.path.join(AI_DIR, "examples")

# Samples across the Jerusalem guide, chosen to cover all audience modes.
SAMPLES = [
    ("muslim-quarter", "student", "storytelling"),
    ("christian-quarter", "tourist", "storytelling"),
    ("armenian-quarter", "child", "emotional"),
    ("bab-al-amud", "short", "neutral"),
    ("maghariba-quarter", "historian", "neutral"),
]

GUIDE_SAMPLES = [
    ("muslim-quarter", "Which Mamluk market leads toward Al-Aqsa?"),
    ("christian-quarter", "Who built the first Holy Sepulchre complex?"),
    ("bab-al-amud", "Which period built the present gate?"),
    ("silwan", "How many people live in Silwan today?"),
]


def _markdown(response, request):
    mode = audiences.get(request.target_audience)
    lines = [
        "# Sample: %s - %s mode" % (response.source.location_name, mode.label),
        "",
        "> Generated by `python3 scripts/generate_examples.py`. Do not edit by hand.",
        "",
        "## Input",
        "",
        "| Field | Value |",
        "|---|---|",
        "| Input location | `%s` (%s) |" % (request.location_id, response.source.location_name),
        "| Target audience | `%s` (%s) |" % (request.target_audience, mode.label),
        "| Tone | `%s` |" % request.tone,
        "| Language | `%s` |" % request.language,
        "| Reviewed source | [`%s`](../../%s) |"
        % (response.source.summary_file, response.source.summary_file),
        "| Full content file | [`%s`](../../%s) |"
        % (response.source.content_file, response.source.content_file),
        "| Generation backend | `%s` (`%s`) |" % (response.model.provider, response.model.name),
        "",
        "## Generated story",
        "",
        "**Title:** %s" % response.title,
        "",
        "**Summary:** %s" % response.summary,
        "",
        "**Narrative** (%d words):" % response.word_count,
        "",
        response.narrative,
        "",
        "## Notes about limitations and missing information",
        "",
    ]

    if response.uncertainty_notes:
        for note in response.uncertainty_notes:
            lines.append("- %s" % note)
    else:
        lines.append("- No gaps were flagged for this request.")

    lines.extend(["", "### Fact-guard result", ""])
    if response.warnings:
        for warning in response.warnings:
            lines.append("- %s" % warning)
    else:
        lines.append(
            "- Clean. Every number and proper noun in the narrative appears in the "
            "reviewed source."
        )

    lines.extend([
        "",
        "### What this sample does not do",
        "",
        "- It uses only the reviewed summary above. Anything absent from that file is "
        "absent from the story.",
        "- Religious traditions and oral heritage stay attributed; they are never "
        "presented as established history.",
    ])
    if request.target_audience == "child":
        lines.append(
            "- Child mode leaves out sieges, destruction and war, so parts of the "
            "location's history are deliberately missing here."
        )
    lines.append("")
    return "\n".join(lines)


def _guide_markdown(rows):
    lines = [
        "# Sample: Heritage Guide questions and answers",
        "",
        "> Generated by `python3 scripts/generate_examples.py`. Do not edit by hand.",
        "",
        "The guide answers only from the reviewed content. The last example shows what "
        "happens when the records do not hold the answer - it refuses rather than "
        "guessing.",
        "",
    ]
    for location_id, question, response in rows:
        lines.extend([
            "## %s - \"%s\"" % (location_id, question),
            "",
            "- **Answered from reviewed source:** %s"
            % ("yes" if response.answered_from_source else "no"),
            "- **Backend:** `%s`" % response.model.provider,
            "",
            "**Answer:**",
            "",
            response.answer,
            "",
        ])
        if response.uncertainty_notes:
            lines.append("**Notes:**")
            lines.append("")
            for note in response.uncertainty_notes:
                lines.append("- %s" % note)
            lines.append("")
    return "\n".join(lines)


def main():
    if not os.path.isdir(EXAMPLES_DIR):
        os.makedirs(EXAMPLES_DIR)

    backend = llm.PROVIDER_NAME if llm.is_configured() else "offline-extractive"
    print("Generating examples with the %s backend..." % backend)

    written = []
    for location_id, audience, tone in SAMPLES:
        request = StoryRequest(
            location_id=location_id, target_audience=audience, tone=tone)
        response = generate_story(request)
        if response.error:
            print("  FAILED %s/%s: %s" % (location_id, audience, response.error))
            return 1

        stem = "%s-%s" % (location_id, audience)
        md_path = os.path.join(EXAMPLES_DIR, stem + ".md")
        json_path = os.path.join(EXAMPLES_DIR, stem + ".json")

        with open(md_path, "w") as handle:
            handle.write(_markdown(response, request))
        with open(json_path, "w") as handle:
            json.dump(
                {"request": {k: v for k, v in vars(request).items() if v is not None},
                 "response": response.to_dict()},
                handle,
                indent=2,
                ensure_ascii=False,
            )
            handle.write("\n")

        written.extend([md_path, json_path])
        print("  %-28s %3d words, %d note(s), %d warning(s)"
              % (stem, response.word_count, len(response.uncertainty_notes),
                 len(response.warnings)))

    rows = []
    for location_id, question in GUIDE_SAMPLES:
        response = answer_question(
            GuideRequest(location_id=location_id, question=question))
        rows.append((location_id, question, response))
    guide_path = os.path.join(EXAMPLES_DIR, "heritage-guide-examples.md")
    with open(guide_path, "w") as handle:
        handle.write(_guide_markdown(rows))
    written.append(guide_path)
    print("  %-28s %d question(s)" % ("heritage-guide-examples", len(rows)))

    print("Wrote %d files to ai/examples/." % len(written))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
