-- =============================================================================
-- Hikaya - GENERATED seed data. Do not edit by hand.
-- =============================================================================
-- Regenerate with:  python3 ai/scripts/export_seed_data.py
--
-- Sources:  content/ai-ready/*-summary.md   (timeline)
--           content/media/media.json        (images)
--
-- Run after database/schema.sql and database/seed.sql:
--   psql -d hikaya -f database/seed-generated.sql
-- =============================================================================

BEGIN;

-- Keep an existing development database compatible with bilingual media metadata.
ALTER TABLE media ADD COLUMN IF NOT EXISTS width INTEGER CHECK (width > 0);
ALTER TABLE media ADD COLUMN IF NOT EXISTS height INTEGER CHECK (height > 0);
ALTER TABLE media ADD COLUMN IF NOT EXISTS subject_ar TEXT;
ALTER TABLE media ADD COLUMN IF NOT EXISTS description_ar TEXT;

DELETE FROM quiz_questions;
DELETE FROM timeline_events;
DELETE FROM media;

-- 48 timeline events ---------------------------------------------------------
INSERT INTO timeline_events
  (id, location_id, period_label, description, sort_year, sort_order, is_tradition, source_file)
VALUES
  ('tl-muslim-quarter-01', 'muslim-quarter', 'Early Islamic period (from 638 CE)', 'Jerusalem came under Muslim rule; the sacred precinct and the city''s institutions developed through successive Umayyad, Abbasid and Fatimid periods.', 638, 0, FALSE, 'content/ai-ready/muslim-quarter-summary.md'),
  ('tl-muslim-quarter-02', 'muslim-quarter', 'Ayyubid period (1187-1250 CE)', 'After Salah al-Din recaptured Jerusalem in 1187, religious and charitable institutions were renewed around the Haram and its approaches.', 1187, 1, FALSE, 'content/ai-ready/muslim-quarter-summary.md'),
  ('tl-muslim-quarter-03', 'muslim-quarter', 'Mamluk era (1250-1517 CE)', 'Sultans and governors endowed madrasas, ribats, fountains, markets and residential buildings along the western and northern approaches to Al-Aqsa.', 1250, 2, FALSE, 'content/ai-ready/muslim-quarter-summary.md'),
  ('tl-muslim-quarter-04', 'muslim-quarter', '1336-1337 CE', 'The governor Tankiz al-Nasiri completed Souq al-Qattanin, its monumental gate and associated commercial and bath complex.', 1336, 3, FALSE, 'content/ai-ready/muslim-quarter-summary.md'),
  ('tl-muslim-quarter-05', 'muslim-quarter', 'Ottoman era (1517-1917 CE)', 'Religious and commercial institutions continued under Ottoman administration, and the quarter remained a centre of Old City life.', 1517, 4, FALSE, 'content/ai-ready/muslim-quarter-summary.md'),
  ('tl-muslim-quarter-06', 'muslim-quarter', 'Modern era', 'Homes, schools, worship routes and family businesses continue amid conservation, access and economic pressures.', 1948, 5, FALSE, 'content/ai-ready/muslim-quarter-summary.md'),
  ('tl-christian-quarter-01', 'christian-quarter', '335 CE', 'Constantine''s Church of the Holy Sepulchre was dedicated around the place central to the church''s sacred traditions.', 335, 0, FALSE, 'content/ai-ready/christian-quarter-summary.md'),
  ('tl-christian-quarter-02', 'christian-quarter', '1009 CE', 'The Fatimid caliph al-Hakim ordered major destruction of the church.', 1009, 1, FALSE, 'content/ai-ready/christian-quarter-summary.md'),
  ('tl-christian-quarter-03', 'christian-quarter', '1040s CE', 'A Byzantine-sponsored restoration reopened the sanctuary, although not in its original complete form.', 1040, 2, FALSE, 'content/ai-ready/christian-quarter-summary.md'),
  ('tl-christian-quarter-04', 'christian-quarter', '1149 CE', 'Crusader rebuilding unified key holy places beneath a Romanesque church, dedicated on 15 July 1149.', 1149, 3, FALSE, 'content/ai-ready/christian-quarter-summary.md'),
  ('tl-christian-quarter-05', 'christian-quarter', '1808-1810 CE', 'A destructive fire was followed by substantial restoration, especially around the rotunda and the structure over the tomb.', 1808, 4, FALSE, 'content/ai-ready/christian-quarter-summary.md'),
  ('tl-christian-quarter-06', 'christian-quarter', 'Ottoman era to present', 'Shared use by several churches became governed by the Status Quo; pilgrimage and local commerce continued around the sanctuary.', 1517, 5, FALSE, 'content/ai-ready/christian-quarter-summary.md'),
  ('tl-armenian-quarter-01', 'armenian-quarter', '4th century CE onward', 'Armenian pilgrimage and religious presence in Jerusalem became established after Armenia''s adoption of Christianity.', 350, 0, FALSE, 'content/ai-ready/armenian-quarter-summary.md'),
  ('tl-armenian-quarter-02', 'armenian-quarter', '12th century CE', 'Much of the present Cathedral of St James took shape during the Crusader period while preserving earlier traditions and material.', 1150, 1, FALSE, 'content/ai-ready/armenian-quarter-summary.md'),
  ('tl-armenian-quarter-03', 'armenian-quarter', '1833 CE', 'The Armenian Patriarchate established a printing press in Jerusalem, an important centre of Armenian-language publishing.', 1833, 2, FALSE, 'content/ai-ready/armenian-quarter-summary.md'),
  ('tl-armenian-quarter-04', 'armenian-quarter', '1850s CE', 'A large pilgrim guesthouse was built; the complex later served other community purposes and now houses the Armenian Museum.', 1850, 3, FALSE, 'content/ai-ready/armenian-quarter-summary.md'),
  ('tl-armenian-quarter-05', 'armenian-quarter', '1919 CE onward', 'Armenian ceramic artists arriving in Jerusalem helped create the city''s distinctive school of hand-painted tile and pottery.', 1919, 4, FALSE, 'content/ai-ready/armenian-quarter-summary.md'),
  ('tl-armenian-quarter-06', 'armenian-quarter', '2022 CE', 'The Edward and Helen Mardigian Museum reopened after major renewal, presenting Armenian Jerusalem and survivor histories.', 2022, 5, FALSE, 'content/ai-ready/armenian-quarter-summary.md'),
  ('tl-maghariba-quarter-01', 'maghariba-quarter', '1187 CE', 'Salah al-Din restored Muslim rule in Jerusalem after the Crusader period.', 1187, 0, FALSE, 'content/ai-ready/maghariba-quarter-summary.md'),
  ('tl-maghariba-quarter-02', 'maghariba-quarter', '1193 CE', 'Historical accounts associate an Ayyubid charitable endowment with housing Maghrebi pilgrims and residents near the sanctuary.', 1193, 1, FALSE, 'content/ai-ready/maghariba-quarter-summary.md'),
  ('tl-maghariba-quarter-03', 'maghariba-quarter', 'Mamluk and Ottoman eras', 'Homes, religious institutions and endowed properties formed a compact community beside Bab al-Maghariba and al-Buraq Wall.', 1250, 2, FALSE, 'content/ai-ready/maghariba-quarter-summary.md'),
  ('tl-maghariba-quarter-04', 'maghariba-quarter', 'British Mandate (1917-1948)', 'Photographs and surveys documented the quarter''s dense stone fabric and North African institutions.', 1917, 3, FALSE, 'content/ai-ready/maghariba-quarter-summary.md'),
  ('tl-maghariba-quarter-05', 'maghariba-quarter', '10-11 June 1967', 'Most of the quarter was demolished and its residents displaced; sources commonly document roughly 135 structures removed.', 10, 4, FALSE, 'content/ai-ready/maghariba-quarter-summary.md'),
  ('tl-maghariba-quarter-06', 'maghariba-quarter', 'Present', 'The open plaza differs radically from the former neighbourhood; family memory and archival evidence preserve its history.', 0, 5, FALSE, 'content/ai-ready/maghariba-quarter-summary.md'),
  ('tl-sheikh-jarrah-01', 'sheikh-jarrah', 'Medieval tradition', 'The neighbourhood name became associated with a tomb traditionally attributed to Hussam al-Din al-Jarrahi, a physician linked in tradition to Salah al-Din.', 0, 0, FALSE, 'content/ai-ready/sheikh-jarrah-summary.md'),
  ('tl-sheikh-jarrah-02', 'sheikh-jarrah', 'Late 19th century', 'Prominent Jerusalem families built stone residences north of the Old City as urban life expanded beyond the walls.', 1850, 1, FALSE, 'content/ai-ready/sheikh-jarrah-summary.md'),
  ('tl-sheikh-jarrah-03', 'sheikh-jarrah', '1922 CE', 'The Isaf al-Nashashibi house was built to a design attributed to architect Spiro Khouri, combining local stone architecture with modern villa planning.', 1922, 2, FALSE, 'content/ai-ready/sheikh-jarrah-summary.md'),
  ('tl-sheikh-jarrah-04', 'sheikh-jarrah', 'British Mandate (1917-1948)', 'Villas, consulates, hospitals and institutions reinforced the district''s modern urban character.', 1917, 3, FALSE, 'content/ai-ready/sheikh-jarrah-summary.md'),
  ('tl-sheikh-jarrah-05', 'sheikh-jarrah', '1954-1956 CE', 'Twenty-eight refugee families entered a housing arrangement involving Jordanian authorities and UNRWA; 28 housing units were completed in 1956.', 1954, 4, FALSE, 'content/ai-ready/sheikh-jarrah-summary.md'),
  ('tl-sheikh-jarrah-06', 'sheikh-jarrah', 'Modern era', 'Community life continues amid prolonged legal, property and displacement pressures that require current verification.', 1948, 5, FALSE, 'content/ai-ready/sheikh-jarrah-summary.md'),
  ('tl-silwan-01', 'silwan', 'Ancient periods', 'The spring and valley supported settlement beside Jerusalem''s historic core; water channels and rock-cut systems belong to several phases.', 0, 0, FALSE, 'content/ai-ready/silwan-summary.md'),
  ('tl-silwan-02', 'silwan', '10th century CE', 'Medieval geographer al-Muqaddasi described the spring and the cultivated landscape below Jerusalem.', 950, 1, FALSE, 'content/ai-ready/silwan-summary.md'),
  ('tl-silwan-03', 'silwan', 'Ottoman era (1517-1917 CE)', 'Silwan was an established village whose residents cultivated irrigated gardens and hillside terraces.', 1517, 2, FALSE, 'content/ai-ready/silwan-summary.md'),
  ('tl-silwan-04', 'silwan', '1920 CE', 'Photographs documented the village''s dense stone houses and terraced relationship to the Kidron Valley.', 1920, 3, FALSE, 'content/ai-ready/silwan-summary.md'),
  ('tl-silwan-05', 'silwan', '20th century', 'Population and building expanded across the slopes while farming and spring memories remained part of local identity.', 1950, 4, FALSE, 'content/ai-ready/silwan-summary.md'),
  ('tl-silwan-06', 'silwan', 'Present', 'Archaeology, tourism, homes and community life occupy the same contested landscape and must not be conflated.', 0, 5, FALSE, 'content/ai-ready/silwan-summary.md'),
  ('tl-at-tur-01', 'at-tur', 'Ancient and late antique periods', 'The ridge served as an eastern approach to Jerusalem and a place of burial, worship and cultivation.', 0, 0, FALSE, 'content/ai-ready/at-tur-summary.md'),
  ('tl-at-tur-02', 'at-tur', '4th century CE', 'Christian pilgrimage buildings were established on the Mount of Olives and near Gethsemane in the Byzantine period.', 350, 1, FALSE, 'content/ai-ready/at-tur-summary.md'),
  ('tl-at-tur-03', 'at-tur', 'Crusader period (1099-1187 CE)', 'Churches and pilgrimage routes were rebuilt or reorganised around sites identified in Christian tradition.', 1099, 2, TRUE, 'content/ai-ready/at-tur-summary.md'),
  ('tl-at-tur-04', 'at-tur', 'Ottoman era (1517-1917 CE)', 'The Palestinian village community and multiple religious institutions continued across the ridge.', 1517, 3, FALSE, 'content/ai-ready/at-tur-summary.md'),
  ('tl-at-tur-05', 'at-tur', '1924 CE', 'The present Basilica of the Agony/Church of All Nations at Gethsemane was consecrated; Antonio Barluzzi designed it above earlier remains.', 1924, 4, FALSE, 'content/ai-ready/at-tur-summary.md'),
  ('tl-at-tur-06', 'at-tur', 'Modern era', 'At-Tur developed into a dense Jerusalem neighbourhood while retaining major sacred sites, cemeteries and panoramic viewpoints.', 1948, 5, FALSE, 'content/ai-ready/at-tur-summary.md'),
  ('tl-bab-al-amud-01', 'bab-al-amud', 'Roman era (117-138 CE)', 'A Roman gate complex was built during the reign of Hadrian as the city was refounded as Aelia Capitolina; remains survive below the present entrance, and the Arabic name is believed to recall the column in its plaza.', 117, 0, TRUE, 'content/ai-ready/bab-al-amud-summary.md'),
  ('tl-bab-al-amud-02', 'bab-al-amud', '6th century CE', 'The Madaba mosaic map represented the northern gate, an internal plaza and a column marking the start of the main north-south street.', 550, 1, FALSE, 'content/ai-ready/bab-al-amud-summary.md'),
  ('tl-bab-al-amud-03', 'bab-al-amud', 'Ottoman era (16th century; 1537-1540 CE)', 'The present gate was built as part of the Ottoman walls commissioned by Sultan Suleiman the Magnificent.', 1550, 2, FALSE, 'content/ai-ready/bab-al-amud-summary.md'),
  ('tl-bab-al-amud-04', 'bab-al-amud', '19th-early 20th centuries', 'Photographs documented the gate as a busy arrival point for people, animals and goods from northern routes.', 19, 3, FALSE, 'content/ai-ready/bab-al-amud-summary.md'),
  ('tl-bab-al-amud-05', 'bab-al-amud', 'Mid-20th century', 'Archaeological work exposed parts of the earlier Roman gate beneath the Ottoman structure.', 1950, 4, FALSE, 'content/ai-ready/bab-al-amud-summary.md'),
  ('tl-bab-al-amud-06', 'bab-al-amud', 'Present', 'The steps and square remain a major Palestinian civic gathering place and threshold to Old City markets.', 0, 5, FALSE, 'content/ai-ready/bab-al-amud-summary.md');

-- 64 media records -----------------------------------------------------------
INSERT INTO media
  (id, location_id, type, url, thumb_url, width, height, subject, subject_ar, description, description_ar, era, pair_role,
   credit, license, license_url, captured_at, source_url, sort_order)
VALUES
  ('muslim-cover', 'muslim-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Souq_al-Qattanin_%D8%B3%D9%88%D9%82_%D8%A7%D9%84%D9%82%D8%B7%D8%A7%D9%86%D9%8A%D9%86_%D8%A7%D9%84%D9%82%D8%AF%D8%B3.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Souq_al-Qattanin_%D8%B3%D9%88%D9%82_%D8%A7%D9%84%D9%82%D8%B7%D8%A7%D9%86%D9%8A%D9%86_%D8%A7%D9%84%D9%82%D8%AF%D8%B3.jpg?width=600', 2048, 3088, 'Souq al-Qattanin', 'سوق القطانين', 'The Mamluk Cotton Merchants’ Market in the Muslim Quarter.', 'يمتد سوق القطانين المملوكي تحت قبوات حجرية متتابعة؛ وتُظهر الصورة الممر التجاري الذي يصل قلب حارة المسلمين بأبواب المسجد الأقصى.', 'modern', 'cover', 'Bekmaw', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', '2009-01-31', 'https://commons.wikimedia.org/wiki/File:Souq_al-Qattanin_%D8%B3%D9%88%D9%82_%D8%A7%D9%84%D9%82%D8%B7%D8%A7%D9%86%D9%8A%D9%86_%D8%A7%D9%84%D9%82%D8%AF%D8%B3.jpg', 0),
  ('christian-cover', 'christian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Christian_Quarter_IMG_0431.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Christian_Quarter_IMG_0431.jpg?width=600', 2736, 3648, 'Christian Quarter street', 'شارع في حارة النصارى', 'St Dimitri’s Road in the Christian Quarter, with St Saviour’s bell tower beyond.', 'يمتد طريق مار ديمتري بين واجهات الحجر المقدسي، ويظهر برج كنيسة المخلّص خلف نسيج حارة النصارى المتقارب.', 'modern', 'cover', 'Deror avi', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', '2008-09-26', 'https://commons.wikimedia.org/wiki/File:Christian_Quarter_IMG_0431.jpg', 0),
  ('armenian-cover', 'armenian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Entrance_to_the_Cathedral_of_Saint_James_in_the_Armenian_Quarter_of_Jerusalem.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Entrance_to_the_Cathedral_of_Saint_James_in_the_Armenian_Quarter_of_Jerusalem.jpg?width=600', 2288, 1712, 'St James Cathedral', 'كاتدرائية مار يعقوب', 'The entrance to St James Cathedral in the Armenian Quarter.', 'مدخل كاتدرائية مار يعقوب بعقده الحجري وواجهته الهادئة داخل حارة الأرمن، مركز الحياة الكنسية الأرمنية المقدسية.', 'modern', 'cover', 'John S Y Lee', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', '2009-05-28', 'https://commons.wikimedia.org/wiki/File:Entrance_to_the_Cathedral_of_Saint_James_in_the_Armenian_Quarter_of_Jerusalem.jpg', 0),
  ('maghariba-cover', 'maghariba-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/19th_century_view_of_Jerusalem%2C_including_the_Moroccan_Quarter.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/19th_century_view_of_Jerusalem%2C_including_the_Moroccan_Quarter.jpg?width=600', 2000, 802, 'Historic Maghariba Quarter', 'حارة المغاربة التاريخية', 'A documented 1864 view including the historic Maghariba Quarter.', 'مشهد موثق سنة 1864 يبيّن النسيج العمراني المنخفض لحارة المغاربة بجوار الحرم القدسي قبل هدم الحارة عام 1967.', 'historical', 'cover', 'Ordnance Survey photograph album', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1864', 'https://commons.wikimedia.org/wiki/File:19th_century_view_of_Jerusalem,_including_the_Moroccan_Quarter.jpg', 0),
  ('sheikh-cover', 'sheikh-jarrah', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kharufe_house_Sheikh_Jarrah.JPG?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Kharufe_house_Sheikh_Jarrah.JPG?width=600', 2006, 1505, 'Kharufe house', 'بيت خروفة', 'A 1940s house in Sheikh Jarrah, photographed in 2010.', 'بيت حجري من أربعينيات القرن العشرين في الشيخ جراح، تحيط به الأشجار وتظهر فيه سمات عمارة الفيلات المقدسية.', 'modern', 'cover', 'Eman', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '2010-05-18', 'https://commons.wikimedia.org/wiki/File:Kharufe_house_Sheikh_Jarrah.JPG', 0),
  ('silwan-cover', 'silwan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/%D9%82%D8%B1%D9%8A%D8%A9_%D8%B3%D9%84%D9%88%D8%A7%D9%86.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/%D9%82%D8%B1%D9%8A%D8%A9_%D8%B3%D9%84%D9%88%D8%A7%D9%86.jpg?width=600', 4032, 3024, 'Silwan village', 'بلدة سلوان', 'The hillside village of Silwan south of the Old City.', 'تتدرج بيوت سلوان الحجرية على السفح جنوب أسوار البلدة القديمة، في مشهد يوضح علاقة البلدة بوادي قدرون.', 'modern', 'cover', 'Ola Watad', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', '2019-11-15', 'https://commons.wikimedia.org/wiki/File:%D9%82%D8%B1%D9%8A%D8%A9_%D8%B3%D9%84%D9%88%D8%A7%D9%86.jpg', 0),
  ('tur-cover', 'at-tur', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem_panorama_from_Mount_of_Olives.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem_panorama_from_Mount_of_Olives.jpg?width=600', 11753, 2039, 'Mount of Olives panorama', 'مطلّة جبل الزيتون', 'The Old City panorama as seen from the Mount of Olives.', 'مشهد بانورامي للبلدة القديمة وقبة الصخرة من جبل الزيتون، يوضح موقع الطور على الحافة الشرقية للقدس.', 'modern', 'cover', 'Daniel Case', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', '2009-04-13', 'https://commons.wikimedia.org/wiki/File:Jerusalem_panorama_from_Mount_of_Olives.jpg', 0),
  ('amud-cover', 'bab-al-amud', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/125307_jerusalem_-_nablus_gate_square_entrance_PikiWiki_Israel.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/125307_jerusalem_-_nablus_gate_square_entrance_PikiWiki_Israel.jpg?width=600', 4032, 3024, 'Damascus Gate', 'باب العامود', 'Bab al-Amud today.', 'واجهة باب العامود العثمانية وساحته المدرّجة اليوم؛ وهو المدخل الشمالي الأبرز إلى أسواق البلدة القديمة.', 'modern', 'cover', 'שלמה רודד', 'CC BY 2.5', 'https://creativecommons.org/licenses/by/2.5', '2025-01-26', 'https://commons.wikimedia.org/wiki/File:125307_jerusalem_-_nablus_gate_square_entrance_PikiWiki_Israel.jpg', 0),
  ('amud-before', 'bab-al-amud', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Damascus_Gate%2C_Jerusalem_LOC_matpc.14337.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Damascus_Gate%2C_Jerusalem_LOC_matpc.14337.jpg?width=600', 7279, 5357, 'Damascus Gate', 'باب العامود', 'Bab al-Amud in 1925.', 'صورة أرشيفية من مجموعة ماتسون توثق باب العامود وساحته سنة 1925 قبل إعادة تشكيل المجال الحضري الحديث.', 'historical', 'before', 'Matson Collection', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1925', 'https://commons.wikimedia.org/wiki/File:Damascus_Gate,_Jerusalem_LOC_matpc.14337.jpg', 1),
  ('amud-after', 'bab-al-amud', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/125307_jerusalem_-_nablus_gate_square_entrance_PikiWiki_Israel.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/125307_jerusalem_-_nablus_gate_square_entrance_PikiWiki_Israel.jpg?width=600', 4032, 3024, 'Damascus Gate', 'باب العامود', 'Bab al-Amud in 2025.', 'مشهد حديث لباب العامود سنة 2025 يتيح مقارنة الواجهة والساحة وحركة المشاة بالصورة التاريخية للموقع نفسه.', 'modern', 'after', 'שלמה רודד', 'CC BY 2.5', 'https://creativecommons.org/licenses/by/2.5', '2025-01-26', 'https://commons.wikimedia.org/wiki/File:125307_jerusalem_-_nablus_gate_square_entrance_PikiWiki_Israel.jpg', 2),
  ('muslim-souq-2014', 'muslim-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Souq%20al-Qattanin%2C%20East%20Jerusalem%2C%20%2816221870911%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Souq%20al-Qattanin%2C%20East%20Jerusalem%2C%20%2816221870911%29.jpg?width=600', 3888, 2592, 'Souq al-Qattanin vaults', 'قبوات سوق القطانين', 'Repeated pointed arches and shop bays inside the fourteenth-century Cotton Merchants’ Market, photographed in 2014.', 'تكشف العقود المدببة المتتابعة والدكاكين الحجرية إيقاع سوق القطانين المملوكي، كما بدا في صورة سنة 2014.', 'modern', NULL, 'yeowatzup', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0/', '2014-12-24', 'https://commons.wikimedia.org/wiki/File:Souq_al-Qattanin,_East_Jerusalem,_(16221870911).jpg', 1),
  ('muslim-street-2015', 'muslim-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Muslim%20Quarter%2C%20Jerusalem%20%2816197844726%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Muslim%20Quarter%2C%20Jerusalem%20%2816197844726%29.jpg?width=600', 2592, 3888, 'Muslim Quarter street', 'زقاق في حارة المسلمين', 'A narrow stone street showing the vertical, lived-in character of the Muslim Quarter in 2015.', 'زقاق حجري ضيق تتراكب فوقه المساكن والفتحات المقوسة، موضحاً الطابع المأهول والكثيف لحارة المسلمين.', 'modern', NULL, 'yeowatzup', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0/', '2015-01-02', 'https://commons.wikimedia.org/wiki/File:Muslim_Quarter,_Jerusalem_(16197844726).jpg', 2),
  ('christian-sepulchre-2015', 'christian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Church%20of%20the%20Holy%20Sepulchre%2C%20Jerusalem%2C%2043.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Church%20of%20the%20Holy%20Sepulchre%2C%20Jerusalem%2C%2043.jpg?width=600', 3264, 2448, 'Holy Sepulchre entrance', 'مدخل كنيسة القيامة', 'The Crusader-period entrance façade and compact courtyard of the Church of the Holy Sepulchre in 2015.', 'تظهر الواجهة الصليبية ذات المدخلين والساحة الصغيرة أمام كنيسة القيامة، وهي مساحة عبور ولقاء للحجاج والسكان.', 'modern', NULL, 'Hoshvilim', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2015-02-11', 'https://commons.wikimedia.org/wiki/File:Church_of_the_Holy_Sepulchre,_Jerusalem,_43.jpg', 1),
  ('christian-sepulchre-1880', 'christian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fiorillo%2C%20L.%20Church%20of%20the%20Holy%20Sepulchre%20%28Jerusalem%29%201880s.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Fiorillo%2C%20L.%20Church%20of%20the%20Holy%20Sepulchre%20%28Jerusalem%29%201880s.jpg?width=600', 2889, 3451, 'Holy Sepulchre courtyard', 'ساحة كنيسة القيامة', 'Luigi Fiorillo’s 1880s view documents the church entrance and courtyard before twentieth-century conservation campaigns.', 'صورة لويجي فيوريلو من ثمانينيات القرن التاسع عشر توثق المدخل والساحة قبل حملات الترميم في القرن العشرين.', 'historical', NULL, 'Luigi Fiorillo', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1880', 'https://commons.wikimedia.org/wiki/File:Fiorillo,_L._Church_of_the_Holy_Sepulchre_(Jerusalem)_1880s.jpg', 2),
  ('armenian-ceramics-2012', 'armenian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Armenian%20Ceramics%20P1130679.JPG?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Armenian%20Ceramics%20P1130679.JPG?width=600', 3000, 4000, 'Armenian ceramics', 'الخزف الأرمني المقدسي', 'Hand-painted Jerusalem Armenian ceramics showing the cobalt, turquoise and floral vocabulary of local workshops.', 'بلاطات وأوانٍ مرسومة يدوياً بألوان الكوبالت والفيروز والزخارف النباتية التي تميز ورش الخزف الأرمني في القدس.', 'modern', NULL, 'Deror Avi', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2012-03-23', 'https://commons.wikimedia.org/wiki/File:Armenian_Ceramics_P1130679.JPG', 1),
  ('armenian-st-james-tilework-2009', 'armenian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Armenian%20Quarter%2C%20Monastery%20of%20St.%20James%20IMG%204955.JPG?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Armenian%20Quarter%2C%20Monastery%20of%20St.%20James%20IMG%204955.JPG?width=600', 3648, 2736, 'Armenian tilework at St James Monastery', 'بلاط أرمني في دير مار يعقوب', 'A dense panel of cobalt and turquoise floral tilework crowns a pointed opening at St James Monastery, joining Armenian craft with the quarter’s architecture.', 'تعلو فتحة مدببة في دير مار يعقوب لوحة كثيفة من البلاط النباتي الأزرق والفيروزي، جامعةً الحرفة الأرمنية بعمارة الحارة.', 'modern', NULL, 'Deror Avi', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2009-06-05', 'https://commons.wikimedia.org/wiki/File:Armenian_Quarter%2C_Monastery_of_St._James_IMG_4955.JPG', 2),
  ('maghariba-quarter-early20c', 'maghariba-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Temple%20area.%20Jerusalem.%20The%20Dome%20of%20the%20Rock%20and%20the%20western%20Temple%20wall.%20LOC%20matpc.05898%20%28cropped%20around%20Mughrabi%20Quarter%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/The%20Temple%20area.%20Jerusalem.%20The%20Dome%20of%20the%20Rock%20and%20the%20western%20Temple%20wall.%20LOC%20matpc.05898%20%28cropped%20around%20Mughrabi%20Quarter%29.jpg?width=600', 2847, 2089, 'Maghariba Quarter before demolition', 'حارة المغاربة قبل الهدم', 'A Matson Collection view records the dense roofs and lanes of the Maghariba Quarter beside the sanctuary before its 1967 demolition.', 'توثق صورة من مجموعة ماتسون السطوح والأزقة المتراصة لحارة المغاربة بجوار الحرم قبل هدمها في حزيران 1967.', 'historical', NULL, 'Matson Collection, Library of Congress', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', 'between 1898 and 1946', 'https://commons.wikimedia.org/wiki/File:The_Temple_area._Jerusalem._The_Dome_of_the_Rock_and_the_western_Temple_wall._LOC_matpc.05898_(cropped_around_Mughrabi_Quarter).jpg', 1),
  ('maghariba-site-2012', 'maghariba-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Western%20Wall%20Plaza%20%2810804490996%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Western%20Wall%20Plaza%20%2810804490996%29.jpg?width=600', 3423, 2394, 'Former quarter site', 'موقع حارة المغاربة السابقة', 'A 2012 view of the broad plaza that now occupies ground where the compact Maghariba Quarter once stood.', 'مشهد سنة 2012 للساحة الواسعة التي تشغل اليوم أرض النسيج السكني السابق لحارة المغاربة.', 'modern', NULL, 'Jorge Láscar', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0/', '2012-09-04', 'https://commons.wikimedia.org/wiki/File:Western_Wall_Plaza_(10804490996).jpg', 2),
  ('sheikh-nashashibi-2010', 'sheikh-jarrah', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/SheikhJarrakhVilaNashashibi105.JPG?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/SheikhJarrakhVilaNashashibi105.JPG?width=600', 2288, 1712, 'Isaf al-Nashashibi house', 'قصر إسعاف النشاشيبي', 'The 1922 Nashashibi villa, photographed in 2010, illustrates Sheikh Jarrah’s stone villa and garden heritage.', 'تُظهر صورة سنة 2010 الفيلا المبنية عام 1922 وحجارتها وحديقتها، وهي من أبرز شواهد عمارة الشيخ جراح.', 'modern', NULL, 'Eman', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '2010-05-18', 'https://commons.wikimedia.org/wiki/File:SheikhJarrakhVilaNashashibi105.JPG', 1),
  ('sheikh-aerial-1931', 'sheikh-jarrah', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Air%20views%20of%20Palestine.%20Jerusalem%20from%20the%20air.%20Newer%20Jerusalem.%20The%20American%20Colony.%20In%20Sheikh%20Jerrah%20Quarter%20LOC%20matpc.22158.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Air%20views%20of%20Palestine.%20Jerusalem%20from%20the%20air.%20Newer%20Jerusalem.%20The%20American%20Colony.%20In%20Sheikh%20Jerrah%20Quarter%20LOC%20matpc.22158.jpg?width=600', 4282, 2788, 'Sheikh Jarrah from the air', 'الشيخ جراح من الجو', 'A 1931 aerial view documents villas, gardens and institutions in the neighbourhood during the British Mandate.', 'صورة جوية سنة 1931 توثق الفيلات والحدائق والمؤسسات وشبكة الطرق في الحي خلال عهد الانتداب البريطاني.', 'historical', NULL, 'Matson Collection, Library of Congress', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1931', 'https://commons.wikimedia.org/wiki/File:Air_views_of_Palestine._Jerusalem_from_the_air._Newer_Jerusalem._The_American_Colony._In_Sheikh_Jerrah_Quarter_LOC_matpc.22158.jpg', 2),
  ('silwan-1920', 'silwan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/VIEW%20OF%20SILWAN%20VILLAGE%20IN%20THE%20KIDRON%20VALLEY%20IN%20JERUSALEM.%20%D7%A6%D7%99%D7%9C%D7%95%D7%9D%20%D7%9B%D7%9C%D7%9C%D7%99%20%D7%A9%D7%9C%20%D7%9B%D7%A4%D7%A8%20%D7%94%D7%A9%D7%99%D7%9C%D7%95%D7%97%20(%D7%A1%D7%99%D7%9C%D7%95%D7%90%D7%9F)%2C%20%D7%91%D7%A0%D7%97%D7%9C%20%D7%A7%D7%99%D7%93%D7%A8%D7%95%D7%9F%20%D7%91%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D.%20(cropped).jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/VIEW%20OF%20SILWAN%20VILLAGE%20IN%20THE%20KIDRON%20VALLEY%20IN%20JERUSALEM.%20%D7%A6%D7%99%D7%9C%D7%95%D7%9D%20%D7%9B%D7%9C%D7%9C%D7%99%20%D7%A9%D7%9C%20%D7%9B%D7%A4%D7%A8%20%D7%94%D7%A9%D7%99%D7%9C%D7%95%D7%97%20(%D7%A1%D7%99%D7%9C%D7%95%D7%90%D7%9F)%2C%20%D7%91%D7%A0%D7%97%D7%9C%20%D7%A7%D7%99%D7%93%D7%A8%D7%95%D7%9F%20%D7%91%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D.%20(cropped).jpg?width=600', 2048, 2034, 'Silwan village and Kidron Valley', 'سلوان ووادي قدرون', 'A 1920 photograph records Silwan’s stone houses and terraced relationship to the Kidron Valley.', 'صورة سنة 1920 توثق بيوت سلوان الحجرية ومدرجات السفح وعلاقتها الطبوغرافية بوادي قدرون.', 'historical', NULL, 'LARSSON', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1920-05-20', 'https://commons.wikimedia.org/wiki/File:VIEW_OF_SILWAN_VILLAGE_IN_THE_KIDRON_VALLEY_IN_JERUSALEM._%D7%A6%D7%99%D7%9C%D7%95%D7%9D_%D7%9B%D7%9C%D7%9C%D7%99_%D7%A9%D7%9C_%D7%9B%D7%A4%D7%A8_%D7%94%D7%A9%D7%99%D7%9C%D7%95%D7%97_(%D7%A1%D7%99%D7%9C%D7%95%D7%90%D7%9F)%2C_%D7%91%D7%A0%D7%97%D7%9C_%D7%A7%D7%99%D7%93%D7%A8%D7%95%D7%9F_%D7%91%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D._(cropped).jpg', 1),
  ('silwan-spring-2009', 'silwan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Outlet%20from%20Hezekiah%27s%20Tunnel-B%20%283782642351%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Outlet%20from%20Hezekiah%27s%20Tunnel-B%20%283782642351%29.jpg?width=600', 3000, 4000, 'Historic water-system outlet', 'مخرج من نظام المياه التاريخي', 'A documented outlet from the rock-cut water system near Ain Silwan, photographed in 2009; individual elements require precise archaeological dating.', 'مخرج موثق من نظام المياه المنحوت قرب عين سلوان؛ ويحتاج تأريخ كل عنصر فيه إلى مرجع أثري متخصص.', 'modern', NULL, 'Ian Scott', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0/', '2009-05-20', 'https://commons.wikimedia.org/wiki/File:Outlet_from_Hezekiah%27s_Tunnel-B_(3782642351).jpg', 2),
  ('tur-gethsemane-2011', 'at-tur', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem%2C%20Church%20of%20Gethsemane%2C%20front%20side.JPG?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem%2C%20Church%20of%20Gethsemane%2C%20front%20side.JPG?width=600', 3312, 4416, 'Church of All Nations', 'كنيسة كل الأمم', 'The columned façade and mosaic pediment of the 1924 Church of All Nations at Gethsemane, photographed in 2011.', 'تظهر الواجهة ذات الأعمدة والفسيفساء لكنيسة كل الأمم، التي دُشنت سنة 1924 عند سفح جبل الزيتون.', 'modern', NULL, 'Juandev', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2011-08-14', 'https://commons.wikimedia.org/wiki/File:Jerusalem,_Church_of_Gethsemane,_front_side.JPG', 1),
  ('tur-gethsemane-1915', 'at-tur', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Garden%20of%20Gethsemane%20and%20Mount%20of%20Olives%20(4879307901).jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Garden%20of%20Gethsemane%20and%20Mount%20of%20Olives%20(4879307901).jpg?width=600', 2725, 2540, 'Gethsemane and Mount of Olives in 1915', 'الجثمانية وجبل الزيتون سنة 1915', 'A 1915 lantern slide records terraced olive plots, paths and religious buildings at Gethsemane and on the Mount of Olives before later urban growth.', 'توثق شريحة فوتوغرافية سنة 1915 مدرجات الزيتون والمسارات والمباني الدينية في الجثمانية وجبل الزيتون قبل التوسع العمراني اللاحق.', 'historical', NULL, 'Oregon State University Special Collections & Archives', 'No known copyright restrictions', 'https://www.flickr.com/commons/usage/', '1915', 'https://commons.wikimedia.org/wiki/File:Garden_of_Gethsemane_and_Mount_of_Olives_(4879307901).jpg', 2),
  ('amud-khan-zait-2018', 'bab-al-amud', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Khan%20Az-zait%20street.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Khan%20Az-zait%20street.jpg?width=600', 5312, 2988, 'Khan al-Zeit street', 'شارع خان الزيت', 'Khan al-Zeit’s roofed commercial route continues south from Bab al-Amud into the Old City markets.', 'يمتد سوق خان الزيت المسقوف جنوباً من باب العامود بين الدكاكين والأقواس إلى شبكة أسواق البلدة القديمة.', 'modern', NULL, 'جنان مريش', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2018-01-03', 'https://commons.wikimedia.org/wiki/File:Khan_Az-zait_street.jpg', 3),
  ('muslim-qattanin-ramadan-2011', 'muslim-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem%20muslim%20quarter%20during%20Ramadan%20Victor%20Grigas%202011%20-1-49.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem%20muslim%20quarter%20during%20Ramadan%20Victor%20Grigas%202011%20-1-49.jpg?width=600', 4860, 3240, 'Souq al-Qattanin during Ramadan', 'سوق القطانين في رمضان', 'Families and shoppers move beneath the vaulted Cotton Merchants’ Market while Ramadan lights and crescent decorations animate its stone shopfronts.', 'تمر العائلات والمتسوقون تحت قبوات سوق القطانين، فيما تضيء زينة رمضان وأهلة الضوء واجهات دكاكينه الحجرية.', 'modern', NULL, 'Victor Grigas', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2011-08-07', 'https://commons.wikimedia.org/wiki/File:Jerusalem_muslim_quarter_during_Ramadan_Victor_Grigas_2011_-1-49.jpg', 3),
  ('muslim-via-dolorosa-2010', 'muslim-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Via%20Dolorosa%20IMG%201502.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Via%20Dolorosa%20IMG%201502.jpg?width=600', 2736, 3648, 'Pilgrims on the Via Dolorosa', 'حجاج في طريق الآلام', 'Pilgrims carry a wooden cross through the narrow stone route of the Via Dolorosa in the Muslim Quarter.', 'يمر حجاج يحملون صليباً خشبياً في المسار الحجري الضيق لطريق الآلام داخل حارة المسلمين.', 'modern', NULL, 'Deror Avi', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2010-05-18', 'https://commons.wikimedia.org/wiki/File:Via_Dolorosa_IMG_1502.jpg', 4),
  ('christian-muristan-fountain-2013', 'christian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Muristan%20Fountain%20Jerusalem%20%281%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Muristan%20Fountain%20Jerusalem%20%281%29.jpg?width=600', 4000, 3000, 'Muristan fountain and market square', 'نافورة وساحة المورستان', 'The Ottoman fountain anchors the Muristan’s market square, surrounded by shops and the everyday movement of the Christian Quarter.', 'تتوسط النافورة العثمانية ساحة سوق المورستان بين الدكاكين وحركة حارة النصارى اليومية.', 'modern', NULL, 'Radosław Botev', 'CC BY 3.0 PL', 'https://creativecommons.org/licenses/by/3.0/pl/deed.en', '2013-05-09', 'https://commons.wikimedia.org/wiki/File:Muristan_Fountain_Jerusalem_(1).jpg', 3),
  ('christian-latin-patriarchate-2011', 'christian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem%20The%20Latin%20Patriarchiate%20%286036331542%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem%20The%20Latin%20Patriarchiate%20%286036331542%29.jpg?width=600', 2515, 1683, 'Latin Patriarchate courtyard', 'فناء بطريركية اللاتين', 'Pointed windows and pale Jerusalem stone frame an interior courtyard of the Latin Patriarchate in the Christian Quarter.', 'تؤطر النوافذ المدببة والحجر المقدسي الفاتح فناءً داخلياً في بطريركية اللاتين بحارة النصارى.', 'modern', NULL, 'brionv', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0/', '2011-08-07', 'https://commons.wikimedia.org/wiki/File:Jerusalem_The_Latin_Patriarchiate_(6036331542).jpg', 4),
  ('armenian-quarter-detail-2014', 'armenian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Armenian%20Quarter%2C%20Jerusalem%20010.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Armenian%20Quarter%2C%20Jerusalem%20010.jpg?width=600', 3264, 2448, 'Armenian ceramic workshop', 'ورشة خزف أرمني', 'A ceramics shop in the Armenian Quarter displays painted tiles beside Armenian inscriptions, linking craft, script and place.', 'يعرض متجر في حارة الأرمن بلاطات مرسومة بجوار كتابات أرمنية، رابطاً الحرفة بالخط والهوية المكانية.', 'modern', NULL, 'Pandukht', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2014-05-05', 'https://commons.wikimedia.org/wiki/File:Armenian_Quarter,_Jerusalem_010.jpg', 3),
  ('armenian-patriarchate-street-2014', 'armenian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Old%20Jerusalem%2C%20The%20Armenian%20Patriarchate%20street.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Old%20Jerusalem%2C%20The%20Armenian%20Patriarchate%20street.jpg?width=600', 3413, 5120, 'Armenian Patriarchate Street', 'شارع بطريركية الأرمن', 'A deep stone arch frames Armenian Patriarchate Street and the bell tower beyond, showing the quarter’s enclosed architectural character.', 'يؤطر عقد حجري عميق شارع بطريركية الأرمن وبرج الجرس، مظهراً الطابع المعماري المغلق للحارة.', 'modern', NULL, 'Ruby1619', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2014-08-16', 'https://commons.wikimedia.org/wiki/File:Old_Jerusalem,_The_Armenian_Patriarchate_street.jpg', 4),
  ('maghariba-quarter-1930s-overview', 'maghariba-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mosque%20%26%20Jews''%20wailing%20place%20LOC%20matpc.16909.tif?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mosque%20%26%20Jews''%20wailing%20place%20LOC%20matpc.16909.tif?width=600', 4648, 3499, 'Maghariba Quarter and al-Buraq Wall in the 1930s', 'حارة المغاربة وحائط البراق في الثلاثينيات', 'A Matson Collection overview from 1934–39 records the Maghariba Quarter’s homes, courtyards and mosque beside al-Buraq Wall, with the Mount of Olives beyond.', 'يوثق مشهد من مجموعة ماتسون بين 1934 و1939 بيوت حارة المغاربة وأفنيتها ومسجدها بجوار حائط البراق، ويظهر جبل الزيتون في الخلف.', 'historical', NULL, 'Matson Collection, Library of Congress', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', 'between 1934 and 1939', 'https://commons.wikimedia.org/wiki/File:Mosque_%26_Jews''_wailing_place_LOC_matpc.16909.tif', 3),
  ('sheikh-umm-kamel-2009', 'sheikh-jarrah', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Umm%20Kamel%20al-Kurd%20in%20Sheikh%20Jarrah%20solidarity%20tent%2C%202009.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Umm%20Kamel%20al-Kurd%20in%20Sheikh%20Jarrah%20solidarity%20tent%2C%202009.jpg?width=600', 3088, 2048, 'Umm Kamel al-Kurd', 'أم كامل الكرد', 'Umm Kamel al-Kurd sits in the Sheikh Jarrah solidarity tent in 2009, a documented image of community presence and steadfastness.', 'تجلس أم كامل الكرد في خيمة التضامن بالشيخ جراح عام 2009؛ صورة موثقة للحضور المجتمعي والصمود.', 'modern', NULL, 'Bekmaw', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2009-01-31', 'https://commons.wikimedia.org/wiki/File:Umm_Kamel_al-Kurd_in_Sheikh_Jarrah_solidarity_tent,_2009.jpg', 3),
  ('silwan-ain-1907', 'silwan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ain%20Silwan.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ain%20Silwan.jpg?width=600', 1734, 1392, 'Ain Silwan in 1907', 'عين سلوان سنة 1907', 'Lewis B. Paton’s published 1907 photograph records masonry and vegetation at Ain Silwan in the early twentieth century.', 'توثق صورة لويس ب. باتون المنشورة عام 1907 البناء الحجري والنباتات عند عين سلوان في مطلع القرن العشرين.', 'historical', NULL, 'Lewis B. Paton', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1907', 'https://commons.wikimedia.org/wiki/File:Ain_Silwan.jpg', 3),
  ('silwan-gardens-1960s', 'silwan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/93086%20jerusalem%20-%20the%20village%20of%20silwan%20PikiWiki%20Israel.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/93086%20jerusalem%20-%20the%20village%20of%20silwan%20PikiWiki%20Israel.jpg?width=600', 3040, 2048, 'Silwan homes and cultivated valley slopes', 'بيوت سلوان وسفوح الوادي المزروعة', 'A view dated between 1967 and 1970 records Silwan’s dense stone homes above cultivated valley plots, preserving the relationship between village and gardens.', 'يوثق مشهد مؤرخ بين 1967 و1970 بيوت سلوان الحجرية الكثيفة فوق قطع الوادي المزروعة، حافظاً العلاقة بين البلدة وبساتينها.', 'historical', NULL, 'Ronnie Kenigsberg', 'CC BY 2.5', 'https://creativecommons.org/licenses/by/2.5/', 'between 1967 and 1970', 'https://commons.wikimedia.org/wiki/File:93086_jerusalem_-_the_village_of_silwan_PikiWiki_Israel.jpg', 4),
  ('tur-gethsemane-olives-2016', 'at-tur', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Garden%20of%20Gethsemane%20Olive%20Trees%20%2825595685200%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Garden%20of%20Gethsemane%20Olive%20Trees%20%2825595685200%29.jpg?width=600', 2988, 5312, 'Olive trees at Gethsemane', 'زيتون الجثمانية', 'Gnarled olive trunks and new growth in the Garden of Gethsemane show the living landscape at the foot of the Mount of Olives.', 'تجمع أشجار الزيتون في الجثمانية بين الجذوع المعمرة والنمو الجديد عند سفح جبل الزيتون.', 'modern', NULL, 'Konrad Summers', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0/', '2016-03-17', 'https://commons.wikimedia.org/wiki/File:Garden_of_Gethsemane_Olive_Trees_(25595685200).jpg', 3),
  ('tur-aerial-2013', 'at-tur', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/2013-Aerial-Mount%20of%20Olives.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/2013-Aerial-Mount%20of%20Olives.jpg?width=600', 5000, 2767, 'Mount of Olives and At-Tur from the air', 'جبل الزيتون والطور من الجو', 'An aerial view places the Mount of Olives cemetery, the At-Tur ridge and surrounding Jerusalem neighbourhoods within one landscape.', 'يجمع المشهد الجوي مقبرة جبل الزيتون وسفح الطور والأحياء المقدسية المحيطة ضمن تضاريس واحدة.', 'modern', NULL, 'Godot13', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2013-03-28', 'https://commons.wikimedia.org/wiki/File:2013-Aerial-Mount_of_Olives.jpg', 4),
  ('amud-gate-2022', 'bab-al-amud', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Damascus%20Gate%20IMG%203146.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Damascus%20Gate%20IMG%203146.jpg?width=600', 5184, 3888, 'Bab al-Amud façade and steps', 'واجهة باب العامود ودرجاته', 'A wide view records the crenellated Ottoman façade, pointed entrance arch and stepped public square of Bab al-Amud.', 'مشهد واسع يوثق شرفات الواجهة العثمانية والعقد المدبب والساحة المدرجة أمام باب العامود.', 'modern', NULL, 'بدارين', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2022-11-08', 'https://commons.wikimedia.org/wiki/File:Damascus_Gate_IMG_3146.jpg', 4),
  ('amud-khan-zait-2019', 'bab-al-amud', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Suk%20Khan%20Az-Zait%2C%202019%20%2805%29.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Suk%20Khan%20Az-Zait%2C%202019%20%2805%29.jpg?width=600', 6016, 4016, 'A confectionery shop in Khan al-Zeit', 'محل حلويات في خان الزيت', 'A confectionery shop and passing shoppers show the contemporary commercial life of Khan al-Zeit beyond Bab al-Amud.', 'يوثق محل الحلويات وحركة المتسوقين الحياة التجارية المعاصرة في سوق خان الزيت خلف باب العامود.', 'modern', NULL, 'Bahnfrend', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2019-04-13', 'https://commons.wikimedia.org/wiki/File:Suk_Khan_Az-Zait,_2019_(05).jpg', 5),
  ('muslim-bab-hutta-2022', 'muslim-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem-Bab-Hutta-st-V1-704.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem-Bab-Hutta-st-V1-704.jpg?width=600', 5472, 3648, 'Bab Hutta Street', 'طريق باب حطة', 'A high-resolution street view follows Bab Hutta’s pale stone paving, steps, pointed doorways and closely spaced residential façades in the Muslim Quarter.', 'يتتبع المشهد الحجري عالي الدقة رصف طريق باب حطة ودرجاته ومداخله المدببة وواجهاته السكنية المتقاربة في حارة المسلمين.', 'modern', NULL, 'Bukvoed', 'CC BY 4.0', 'https://creativecommons.org/licenses/by/4.0/', '2022-09-26', 'https://commons.wikimedia.org/wiki/File:Jerusalem-Bab-Hutta-st-V1-704.jpg', 5),
  ('muslim-qattanin-2015', 'muslim-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/%D7%A9%D7%95%D7%A7%20%D7%94%D7%9B%D7%95%D7%AA%D7%A0%D7%94.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/%D7%A9%D7%95%D7%A7%20%D7%94%D7%9B%D7%95%D7%AA%D7%A0%D7%94.jpg?width=600', 3736, 5364, 'Souq al-Qattanin passage', 'ممر سوق القطانين', 'Light filters through the long vaulted passage of Souq al-Qattanin, revealing pointed arches, stone shop bays and the market’s carefully ordered Mamluk geometry.', 'يتسلل الضوء في ممر سوق القطانين المقبب، كاشفاً العقود المدببة وواجهات الدكاكين الحجرية والإيقاع الهندسي المملوكي المنظم.', 'modern', NULL, 'אדם יהב', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2015-12-15', 'https://commons.wikimedia.org/wiki/File:%D7%A9%D7%95%D7%A7_%D7%94%D7%9B%D7%95%D7%AA%D7%A0%D7%94.jpg', 6),
  ('muslim-khan-zait-1879', 'muslim-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem%20khan%20ez-zait%201880.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem%20khan%20ez-zait%201880.jpg?width=600', 2838, 4000, 'Khan al-Zait, historical engraving', 'سوق خان الزيت في نقش تاريخي', 'Harry Fenn’s 1877–79 engraving looks from the south toward the Damascus Gate route, recording Khan al-Zait as a busy, shaded commercial street rather than an empty monument.', 'ينظر نقش هاري فن المؤرخ بين 1877 و1879 من الجنوب نحو طريق باب العامود، موثقاً خان الزيت شارعاً تجارياً مظللاً وحياً لا معلماً معزولاً.', 'historical', NULL, 'Harry Fenn', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1877–79', 'https://commons.wikimedia.org/wiki/File:Jerusalem_khan_ez-zait_1880.jpg', 7),
  ('christian-muristan-life-2016', 'christian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Christian%20Quarter%20IMG%208163.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Christian%20Quarter%20IMG%208163.jpg?width=600', 2448, 3264, 'Daily life in the Muristan', 'الحياة اليومية في المورستان', 'Tables, awnings and stone façades show the Muristan as a lived market space where cafés, shops and visitors share the historic courtyard network.', 'تُظهر الطاولات والمظلات والواجهات الحجرية المورستان فضاءً سوقياً حياً تتقاسم فيه المقاهي والدكاكين والزوار شبكة الساحات التاريخية.', 'modern', NULL, 'יוסף חטף סגול', 'CC0 1.0', 'https://creativecommons.org/publicdomain/zero/1.0/', '2016-09-01', 'https://commons.wikimedia.org/wiki/File:Christian_Quarter_IMG_8163.jpg', 5),
  ('christian-muristan-1862', 'christian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ruins%20of%20the%20Muristan%20with%20the%20church%20of%20the%20Holy%20Sepulchre%20(1862).jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Ruins%20of%20the%20Muristan%20with%20the%20church%20of%20the%20Holy%20Sepulchre%20(1862).jpg?width=600', 3510, 2550, 'Muristan and Holy Sepulchre, 1862', 'المورستان وكنيسة القيامة سنة 1862', 'This 1862 archival view records the Muristan’s ruins with the Church of the Holy Sepulchre beyond, preserving an urban layer before later redevelopment.', 'يوثق هذا المشهد الأرشيفي سنة 1862 أطلال المورستان وكنيسة القيامة خلفها، حافظاً طبقة عمرانية سبقت أعمال التطوير اللاحقة.', 'historical', NULL, 'Unknown photographer', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1862', 'https://commons.wikimedia.org/wiki/File:Ruins_of_the_Muristan_with_the_church_of_the_Holy_Sepulchre_(1862).jpg', 6),
  ('christian-anointing-stone-2012', 'christian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Detail%20of%20wall%20behind%20The%20Stone%20of%20Anointing%20-%20The%20Church%20of%20the%20Holy%20Sepulchre%20(10805707205).jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Detail%20of%20wall%20behind%20The%20Stone%20of%20Anointing%20-%20The%20Church%20of%20the%20Holy%20Sepulchre%20(10805707205).jpg?width=600', 4288, 2848, 'Stone of Anointing setting', 'موضع حجر الطيب', 'Lamps, polished stone and the mosaic-lined wall behind the venerated Stone of Anointing reveal the dense devotional detail inside the Church of the Holy Sepulchre.', 'تكشف القناديل والحجر المصقول والجدار المكسو بالفسيفساء خلف حجر الطيب المبجل كثافة التفاصيل التعبدية داخل كنيسة القيامة.', 'modern', NULL, 'Jorge Láscar', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0/', '2012-09-05', 'https://commons.wikimedia.org/wiki/File:Detail_of_wall_behind_The_Stone_of_Anointing_-_The_Church_of_the_Holy_Sepulchre_(10805707205).jpg', 7),
  ('armenian-st-james-street-2012', 'armenian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Old%20Jerusalem%20Armenian%20Quarter%20St.%20James%20street.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Old%20Jerusalem%20Armenian%20Quarter%20St.%20James%20street.jpg?width=600', 2303, 3191, 'St James Street', 'شارع مار يعقوب', 'The narrow stone street beside St James Cathedral shows heavy masonry, restrained openings and the quiet institutional edge of the Armenian Quarter.', 'يُظهر الشارع الحجري الضيق بجوار كاتدرائية مار يعقوب سماكة البناء وفتحات الواجهات المحدودة والطابع المؤسسي الهادئ لحارة الأرمن.', 'modern', NULL, 'Shirleyzer', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2012-02-26', 'https://commons.wikimedia.org/wiki/File:Old_Jerusalem_Armenian_Quarter_St._James_street.jpg', 5),
  ('armenian-monastery-courtyard-2009', 'armenian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Armenian%20Quarter%2C%20Monastery%20of%20St.%20James%20IMG%204940.JPG?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Armenian%20Quarter%2C%20Monastery%20of%20St.%20James%20IMG%204940.JPG?width=600', 3648, 2736, 'Monastery of St James courtyard', 'فناء دير مار يعقوب', 'A paved monastic courtyard, arched entries and pale limestone walls illustrate the inward-facing communal architecture around St James.', 'يوضح الفناء المرصوف والمداخل المقوسة وجدران الحجر الجيري الفاتح العمارة الجماعية المنفتحة إلى الداخل حول دير مار يعقوب.', 'modern', NULL, 'Deror Avi', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2009-06-05', 'https://commons.wikimedia.org/wiki/File:Armenian_Quarter%2C_Monastery_of_St._James_IMG_4940.JPG', 6),
  ('armenian-stair-alley-2014', 'armenian-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Alley%20of%20Stairs%2C%20Armenian%20Quarter%2C%20Jerusalem%2C%20%D7%A1%D7%9E%D7%98%D7%AA%20%D7%9E%D7%93%D7%A8%D7%92%D7%95%D7%AA%2C%20%D7%94%D7%A8%D7%95%D7%91%D7%A2%20%D7%94%D7%90%D7%A8%D7%9E%D7%A0%D7%99%2C%20%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D%20-%20panoramio.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Alley%20of%20Stairs%2C%20Armenian%20Quarter%2C%20Jerusalem%2C%20%D7%A1%D7%9E%D7%98%D7%AA%20%D7%9E%D7%93%D7%A8%D7%92%D7%95%D7%AA%2C%20%D7%94%D7%A8%D7%95%D7%91%D7%A2%20%D7%94%D7%90%D7%A8%D7%9E%D7%A0%D7%99%2C%20%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D%20-%20panoramio.jpg?width=600', 3216, 4288, 'Stepped Armenian Quarter alley', 'زقاق مدرج في حارة الأرمن', 'A steep stepped alley passes between high stone walls and arched thresholds, showing how the Armenian Quarter negotiates the Old City’s changing levels.', 'يمر زقاق شديد الانحدار بين جدران حجرية عالية وعتبات مقوسة، موضحاً كيف تتعامل حارة الأرمن مع تفاوت مناسيب البلدة القديمة.', 'modern', NULL, 'ekeidar', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2014-09-25', 'https://commons.wikimedia.org/wiki/File:Alley_of_Stairs%2C_Armenian_Quarter%2C_Jerusalem%2C_%D7%A1%D7%9E%D7%98%D7%AA_%D7%9E%D7%93%D7%A8%D7%92%D7%95%D7%AA%2C_%D7%94%D7%A8%D7%95%D7%91%D7%A2_%D7%94%D7%90%D7%A8%D7%9E%D7%A0%D7%99%2C_%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D_-_panoramio.jpg', 7),
  ('maghariba-al-buraq-1950', 'maghariba-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/De%20klaagmuur%2C%20Bestanddeelnr%20255-5389.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/De%20klaagmuur%2C%20Bestanddeelnr%20255-5389.jpg?width=600', 2614, 2613, 'Al-Buraq Wall lane in 1950', 'ممر حائط البراق سنة 1950', 'Willem van de Poll’s 1950 photograph records the narrow paved space beside al-Buraq Wall before the Maghariba Quarter was demolished and the present plaza created.', 'توثق صورة فيليم فان دي بول سنة 1950 الممر المرصوف الضيق بجوار حائط البراق قبل هدم حارة المغاربة وإنشاء الساحة الحالية.', 'historical', NULL, 'Willem van de Poll', 'CC0 1.0', 'https://creativecommons.org/publicdomain/zero/1.0/', '1950', 'https://commons.wikimedia.org/wiki/File:De_klaagmuur%2C_Bestanddeelnr_255-5389.jpg', 4),
  ('maghariba-lane-1930s', 'maghariba-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mosque%20%26%20Jews''%20wailing%20place%20LOC%20matpc.16910.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mosque%20%26%20Jews''%20wailing%20place%20LOC%20matpc.16910.jpg?width=600', 3023, 3917, 'Maghariba Quarter lane beside al-Buraq Wall', 'ممر حارة المغاربة بجوار حائط البراق', 'A Matson Collection photograph from 1934–39 documents the built edge, homes and confined lane beside al-Buraq Wall before the neighbourhood’s 1967 demolition.', 'توثق صورة من مجموعة ماتسون بين 1934 و1939 حافة الحارة المبنية وبيوتها والممر الضيق بجوار حائط البراق قبل هدم الحي سنة 1967.', 'historical', NULL, 'Matson Collection, Library of Congress', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', 'between 1934 and 1939', 'https://commons.wikimedia.org/wiki/File:Mosque_%26_Jews''_wailing_place_LOC_matpc.16910.jpg', 5),
  ('maghariba-panorama-early20c', 'maghariba-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20area%2C%20Mosque%20of%20Omar%20(i.e.%2C%20Dome%20of%20the%20Rock)%20and%20Jerusalem%20LOC%20matpc.06075.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Temple%20area%2C%20Mosque%20of%20Omar%20(i.e.%2C%20Dome%20of%20the%20Rock)%20and%20Jerusalem%20LOC%20matpc.06075.jpg?width=600', 5502, 3851, 'Historic panorama of the Maghariba Quarter setting', 'مشهد تاريخي لموضع حارة المغاربة', 'This early twentieth-century panorama locates the low-rise Maghariba Quarter fabric beside the Haram al-Sharif and the Dome of the Rock within Jerusalem’s broader topography.', 'يحدد هذا المشهد البانورامي من أوائل القرن العشرين موقع نسيج حارة المغاربة المنخفض بجوار الحرم الشريف وقبة الصخرة ضمن طبوغرافية القدس.', 'historical', NULL, 'Matson Collection, Library of Congress', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', 'between 1898 and 1946', 'https://commons.wikimedia.org/wiki/File:Temple_area%2C_Mosque_of_Omar_(i.e.%2C_Dome_of_the_Rock)_and_Jerusalem_LOC_matpc.06075.jpg', 6),
  ('maghariba-gate-bridge-2011', 'maghariba-quarter', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/PikiWiki%20Israel%2013506%20Jerusalem%20Mughrabi%20Gate%20Bridge.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/PikiWiki%20Israel%2013506%20Jerusalem%20Mughrabi%20Gate%20Bridge.jpg?width=600', 2048, 1536, 'Bab al-Maghariba access bridge', 'جسر الوصول إلى باب المغاربة', 'The modern access bridge leading to Bab al-Maghariba is shown as a present-day structure distinct from the Palestinian quarter erased from the adjoining site in 1967.', 'يظهر جسر الوصول الحديث إلى باب المغاربة بوصفه منشأة معاصرة مختلفة عن الحارة الفلسطينية التي أزيلت من الموقع المجاور سنة 1967.', 'modern', NULL, 'Dr. Avishai Teicher', 'CC BY 2.5', 'https://creativecommons.org/licenses/by/2.5/', '2011-06-21', 'https://commons.wikimedia.org/wiki/File:PikiWiki_Israel_13506_Jerusalem_Mughrabi_Gate_Bridge.jpg', 7),
  ('sheikh-camp-1918', 'sheikh-jarrah', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/6th%20Australian%20light-horse%20regiment%20camped%20in%20Sheikh%20Jarrah%2C%20on%20the%20road%20leading%20to%20Mt.%20Scopus%2C%201918%20LOC%20matpc.08115.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/6th%20Australian%20light-horse%20regiment%20camped%20in%20Sheikh%20Jarrah%2C%20on%20the%20road%20leading%20to%20Mt.%20Scopus%2C%201918%20LOC%20matpc.08115.jpg?width=600', 5866, 4341, 'Sheikh Jarrah road landscape in 1918', 'مشهد طريق الشيخ جراح سنة 1918', 'A 1918 Matson Collection photograph records the open road toward Mount Scopus and a temporary military camp, before later urban growth filled much of the surrounding land.', 'توثق صورة من مجموعة ماتسون سنة 1918 الطريق المفتوح نحو جبل المشارف ومعسكراً عسكرياً مؤقتاً، قبل أن يملأ التوسع العمراني لاحقاً مساحات واسعة حوله.', 'historical', NULL, 'Matson Collection, Library of Congress', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1918', 'https://commons.wikimedia.org/wiki/File:6th_Australian_light-horse_regiment_camped_in_Sheikh_Jarrah%2C_on_the_road_leading_to_Mt._Scopus%2C_1918_LOC_matpc.08115.jpg', 4),
  ('sheikh-home-2021', 'sheikh-jarrah', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/A%20home%20under%20threat%20of%20confiscation%20-%20Sheikh%20Jarrah.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/A%20home%20under%20threat%20of%20confiscation%20-%20Sheikh%20Jarrah.jpg?width=600', 2048, 1536, 'A resident home in Karm al-Jaouni', 'منزل مقدسي في كرم الجاعوني', 'A stone home carrying solidarity signs documents the lived residential character of Karm al-Jaouni and the displacement pressure faced by Palestinian families in Sheikh Jarrah.', 'يوثق منزل حجري يحمل لافتات تضامن الطابع السكني الحي لكرم الجاعوني وضغوط التهجير التي تواجهها العائلات الفلسطينية في الشيخ جراح.', 'modern', NULL, 'Osps7', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0/', '2021-05-09', 'https://commons.wikimedia.org/wiki/File:A_home_under_threat_of_confiscation_-_Sheikh_Jarrah.jpg', 5),
  ('sheikh-street-2023', 'sheikh-jarrah', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/SheikhJarrahMay232023.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/SheikhJarrahMay232023.jpg?width=600', 2605, 1735, 'Sheikh Jarrah street and stone homes', 'شارع وبيوت حجرية في الشيخ جراح', 'A contemporary street view shows Jerusalem-stone houses, boundary walls, trees and the layered residential scale of Sheikh Jarrah.', 'يُظهر مشهد معاصر بيوت الحجر المقدسي والجدران والأشجار والمقياس السكني المتدرج لحي الشيخ جراح.', 'modern', NULL, 'Hagai Agmon-Snir', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2023-05-23', 'https://commons.wikimedia.org/wiki/File:SheikhJarrahMay232023.jpg', 6),
  ('sheikh-american-colony-2024', 'sheikh-jarrah', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/121644%20jerusalem%20the%20american%20colony%20PikiWiki%20Israel.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/121644%20jerusalem%20the%20american%20colony%20PikiWiki%20Israel.jpg?width=600', 1760, 3812, 'American Colony historic institution', 'مبنى الكولونية الأمريكية التاريخي', 'The stone entrance and garden setting of the American Colony mark one of Sheikh Jarrah’s long-standing institutions and its role in Jerusalem’s photographic and social history.', 'يشير المدخل الحجري والحديقة المحيطة بمبنى الكولونية الأمريكية إلى إحدى مؤسسات الشيخ جراح الراسخة ودورها في تاريخ القدس الفوتوغرافي والاجتماعي.', 'modern', NULL, 'Israel Preker', 'CC BY 2.5', 'https://creativecommons.org/licenses/by/2.5/', '2024-11-20', 'https://commons.wikimedia.org/wiki/File:121644_jerusalem_the_american_colony_PikiWiki_Israel.jpg', 7),
  ('silwan-ordnance-1864', 'silwan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/SilwanOrdnanceSurvey1865.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/SilwanOrdnanceSurvey1865.jpg?width=600', 1600, 1068, 'Silwan during the Ordnance Survey', 'سلوان في المسح الطبوغرافي سنة 1864', 'C. W. Wilson’s 1864 survey photograph records Silwan’s clustered stone houses and cultivated slopes, offering an early visual document of the village landscape.', 'توثق صورة سي. دبليو. ويلسون للمسح سنة 1864 بيوت سلوان الحجرية المتجمعة وسفوحها المزروعة، مقدمةً وثيقة بصرية مبكرة لمشهد القرية.', 'historical', NULL, 'C. W. Wilson', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1864-01-01', 'https://commons.wikimedia.org/wiki/File:SilwanOrdnanceSurvey1865.jpg', 5),
  ('silwan-panorama-2011', 'silwan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20of%20the%20Kidron%20Valley%20and%20Silwan%20Village%20(5767264013).jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Panorama%20of%20the%20Kidron%20Valley%20and%20Silwan%20Village%20(5767264013).jpg?width=600', 2526, 1162, 'Kidron Valley and Silwan panorama', 'بانوراما وادي قدرون وسلوان', 'A broad panorama places Silwan’s dense hillside homes opposite the Kidron Valley, making the village’s steep topography and relationship to the Old City legible.', 'تضع بانوراما واسعة بيوت سلوان الكثيفة على السفح مقابل وادي قدرون، موضحةً طبوغرافية البلدة الشديدة الانحدار وعلاقتها بالبلدة القديمة.', 'modern', NULL, 'Ian Scott', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0/', '2011-05-28', 'https://commons.wikimedia.org/wiki/File:Panorama_of_the_Kidron_Valley_and_Silwan_Village_(5767264013).jpg', 6),
  ('silwan-hillside-2021', 'silwan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Silwan.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Silwan.jpg?width=600', 4624, 3472, 'Silwan hillside homes', 'بيوت سلوان على السفح', 'Closely packed limestone homes, terraces and retaining walls trace the inhabited slope of Silwan in a high-resolution contemporary view.', 'ترسم البيوت المتقاربة من الحجر الجيري والمدرجات والجدران الاستنادية ملامح سفح سلوان المأهول في مشهد معاصر عالي الدقة.', 'modern', NULL, 'Yasmine.shal', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2021-03-06', 'https://commons.wikimedia.org/wiki/File:Silwan.jpg', 7),
  ('tur-augusta-victoria-1912', 'at-tur', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/AUGUSTA%20VICTORIA%20HOSPITAL%20NEAR%20MOUNT%20SCOPUS%20IN%20JERUSALEM.%20(COURTESY%20OF%20AMERICAN%20COLONY)%20%D7%91%D7%99%D7%AA%20%D7%94%D7%97%D7%95%D7%9C%D7%99%D7%9D%20%22%D7%90%D7%92%D7%95%D7%A1%D7%98%D7%94%20%D7%95%D7%99%D7%A7%D7%98%D7%95%D7%A8%D7%99%D7%94%22%20%D7%91%D7%94%D7%A8%20%D7%94%D7%A6%D7%95%D7%A4%D7%99%D7%9D%20%D7%91%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D.D826-112.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/AUGUSTA%20VICTORIA%20HOSPITAL%20NEAR%20MOUNT%20SCOPUS%20IN%20JERUSALEM.%20(COURTESY%20OF%20AMERICAN%20COLONY)%20%D7%91%D7%99%D7%AA%20%D7%94%D7%97%D7%95%D7%9C%D7%99%D7%9D%20%22%D7%90%D7%92%D7%95%D7%A1%D7%98%D7%94%20%D7%95%D7%99%D7%A7%D7%98%D7%95%D7%A8%D7%99%D7%94%22%20%D7%91%D7%94%D7%A8%20%D7%94%D7%A6%D7%95%D7%A4%D7%99%D7%9D%20%D7%91%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D.D826-112.jpg?width=600', 3066, 2052, 'Augusta Victoria complex in 1912', 'مجمع أوغستا فكتوريا سنة 1912', 'An early photograph records the hospital and church complex on the Jerusalem ridge, with its tower rising above open slopes before later urban development.', 'توثق صورة مبكرة مجمع المستشفى والكنيسة على تلة القدس، وبرجه المرتفع فوق السفوح المفتوحة قبل التوسع العمراني اللاحق.', 'historical', NULL, 'Eric Matson, American Colony Photo Department', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1912-07-01', 'https://commons.wikimedia.org/wiki/File:AUGUSTA_VICTORIA_HOSPITAL_NEAR_MOUNT_SCOPUS_IN_JERUSALEM._(COURTESY_OF_AMERICAN_COLONY)_%D7%91%D7%99%D7%AA_%D7%94%D7%97%D7%95%D7%9C%D7%99%D7%9D_%22%D7%90%D7%92%D7%95%D7%A1%D7%98%D7%94_%D7%95%D7%99%D7%A7%D7%98%D7%95%D7%A8%D7%99%D7%94%22_%D7%91%D7%94%D7%A8_%D7%94%D7%A6%D7%95%D7%A4%D7%99%D7%9D_%D7%91%D7%99%D7%A8%D7%95%D7%A9%D7%9C%D7%99%D7%9D.D826-112.jpg', 5),
  ('tur-west-view-early20c', 'at-tur', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mount%20of%20Olives%20(Jebel%20Et-Tur)%20etc.%20Mount%20of%20Olives%20from%20the%20west%20LOC%20matpc.07509.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Mount%20of%20Olives%20(Jebel%20Et-Tur)%20etc.%20Mount%20of%20Olives%20from%20the%20west%20LOC%20matpc.07509.jpg?width=600', 5397, 3997, 'Jabal al-Tur from the west', 'جبل الطور من الغرب', 'A Matson Collection view from 1898–1914 records Jabal al-Tur’s western slope, paths, religious buildings and terraced terrain before modern construction.', 'يوثق مشهد من مجموعة ماتسون بين 1898 و1914 السفح الغربي لجبل الطور ومساراته ومبانيه الدينية وأرضه المدرجة قبل البناء الحديث.', 'historical', NULL, 'Matson Collection, Library of Congress', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', 'between 1898 and 1914', 'https://commons.wikimedia.org/wiki/File:Mount_of_Olives_(Jebel_Et-Tur)_etc._Mount_of_Olives_from_the_west_LOC_matpc.07509.jpg', 6),
  ('tur-neighbourhood-2023', 'at-tur', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/AtTurMountOfOlivesMay232023%2006.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/AtTurMountOfOlivesMay232023%2006.jpg?width=600', 4000, 2668, 'At-Tur neighbourhood on the Mount of Olives', 'حي الطور على جبل الزيتون', 'A contemporary high-resolution view shows At-Tur as a living Palestinian neighbourhood of dense stone housing layered across the Mount of Olives ridge.', 'يُظهر مشهد معاصر عالي الدقة الطور حياً فلسطينياً حياً تتدرج مساكنه الحجرية الكثيفة على تلة جبل الزيتون.', 'modern', NULL, 'Hagai Agmon-Snir', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0/', '2023-05-23', 'https://commons.wikimedia.org/wiki/File:AtTurMountOfOlivesMay232023_06.jpg', 7),
  ('amud-market-1920', 'bab-al-amud', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Around%20the%20city%20wall%20(Jerusalem).%20Damascus%20Gate.%20Bedouins%20unloading%20wheat-ladened%20camels%20LOC%20matpc.02520.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Around%20the%20city%20wall%20(Jerusalem).%20Damascus%20Gate.%20Bedouins%20unloading%20wheat-ladened%20camels%20LOC%20matpc.02520.jpg?width=600', 4168, 2893, 'Bab al-Amud market activity in 1920', 'الحركة التجارية عند باب العامود سنة 1920', 'A 1920 Matson Collection photograph shows wheat-laden camels being unloaded outside Bab al-Amud, documenting the gate plaza as a regional arrival and trading space.', 'تظهر صورة من مجموعة ماتسون سنة 1920 تفريغ حمولة القمح من الجمال خارج باب العامود، موثقةً الساحة فضاءً للوصول والتجارة الإقليمية.', 'historical', NULL, 'Matson Collection, Library of Congress', 'Public domain', 'https://creativecommons.org/publicdomain/mark/1.0/', '1920', 'https://commons.wikimedia.org/wiki/File:Around_the_city_wall_(Jerusalem)._Damascus_Gate._Bedouins_unloading_wheat-ladened_camels_LOC_matpc.02520.jpg', 6),
  ('amud-wide-2019', 'bab-al-amud', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem-Damascus-Gate-KC-644.jpg?width=1600', 'https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem-Damascus-Gate-KC-644.jpg?width=600', 5472, 3648, 'Wide view of Bab al-Amud', 'مشهد واسع لباب العامود', 'A crisp wide view captures the Ottoman gate’s crenellations, flanking towers, pointed portal and the stepped civic plaza that gathers below it.', 'يلتقط مشهد واسع وواضح شرفات البوابة العثمانية وبرجيها والعقد المدبب والساحة العامة المدرجة الممتدة أمامها.', 'modern', NULL, 'Bukvoed', 'CC BY 4.0', 'https://creativecommons.org/licenses/by/4.0/', '2019-10-21', 'https://commons.wikimedia.org/wiki/File:Jerusalem-Damascus-Gate-KC-644.jpg', 7);

-- 40 quiz questions ----------------------------------------------------------
INSERT INTO quiz_questions
  (id, location_id, question, options, answer_index, explanation, source_note, sort_order)
VALUES
  ('quiz-muslim-1', 'muslim-quarter', 'Which Mamluk market forms a monumental approach toward Al-Aqsa?', ARRAY['Souq al-Qattanin', 'Souq al-Bazaar', 'Khan al-Zeit', 'Muristan'], 0, 'Souq al-Qattanin is a vaulted Mamluk market whose eastern gate opens toward the Haram al-Sharif/Al-Aqsa compound.', 'Muslim Quarter §4–5; Museum With No Frontiers, Suq al-Qattanin', 0),
  ('quiz-muslim-2', 'muslim-quarter', 'Under which governor was Souq al-Qattanin completed in 1336–1337?', ARRAY['Salah al-Din', 'Tankiz al-Nasiri', 'Sultan Suleiman', 'Emperor Constantine'], 1, 'The market and associated complex were completed under the Mamluk governor Tankiz al-Nasiri in 737 AH/1336–1337 CE.', 'Muslim Quarter §2 and §5; Museum With No Frontiers', 1),
  ('quiz-muslim-3', 'muslim-quarter', 'Which architectural detail should visitors look for at the Qattanin entrance?', ARRAY['A glass curtain wall', 'Timber pagoda roofs', 'Alternating stone colours and inscription bands', 'A freestanding marble obelisk'], 2, 'The monumental entrance uses coloured stonework, carving and inscription bands typical of prestigious Mamluk portals.', 'Muslim Quarter §5 and §9; Jerusalem Studies, Khan Tankaz', 2),
  ('quiz-muslim-4', 'muslim-quarter', 'Why is the Muslim Quarter described as more than an archaeological district?', ARRAY['It has no historic buildings', 'It is a lived neighbourhood of homes, schools, worship and trade', 'It opens only during festivals', 'It was built entirely after 1948'], 1, 'Its heritage includes continuing residential, educational, religious and commercial life, not monuments alone.', 'Muslim Quarter §1 and §3', 3),
  ('quiz-muslim-5', 'muslim-quarter', 'Which Christian devotional route crosses part of the quarter?', ARRAY['Camino de Santiago', 'Via Dolorosa', 'Appian Way', 'King''s Highway'], 1, 'The Via Dolorosa passes through the quarter, adding a Christian pilgrimage route to its overlapping urban histories.', 'Muslim Quarter §3 and §6', 4),
  ('quiz-christian-1', 'christian-quarter', 'Which arrangement regulates shared responsibilities at the Church of the Holy Sepulchre?', ARRAY['The Status Quo', 'The waqf deed', 'The guild charter', 'The city wall code'], 0, 'Several Christian communities share spaces and responsibilities under the historic Status Quo arrangements.', 'Christian Quarter §3 and §5', 0),
  ('quiz-christian-2', 'christian-quarter', 'In which year was Constantine''s Holy Sepulchre complex dedicated?', ARRAY['638', '1009', '335', '1149'], 2, 'The Constantinian church was dedicated in 335 CE over a site identified in Christian tradition with Calvary and the tomb.', 'Christian Quarter §2; Oxford Reference, Church of the Holy Sepulchre', 1),
  ('quiz-christian-3', 'christian-quarter', 'What major architectural phase was dedicated in 1149?', ARRAY['The Ottoman walls', 'The Crusader rebuilding of the Holy Sepulchre', 'The Armenian printing press', 'The Church of All Nations'], 1, 'Crusader builders unified major sacred spaces into much of the Romanesque church form visible today.', 'Christian Quarter §2; JSAH Crusader reconstruction study', 2),
  ('quiz-christian-4', 'christian-quarter', 'What should visitors notice on the church''s entrance façade?', ARRAY['Two Romanesque portals, one sealed', 'Four minarets', 'An Ottoman clock tower', 'A modern glass dome'], 0, 'The entrance has paired Crusader-period Romanesque portals; one remains sealed while the other is used.', 'Christian Quarter §5 and §9', 3),
  ('quiz-christian-5', 'christian-quarter', 'Why can circulation inside the church change without notice?', ARRAY['The floor is permanently flooded', 'Active services and processions share the building', 'Visitors must follow a fixed museum tour', 'The building closes every afternoon'], 1, 'It is a living, shared place of worship, so ceremonies and processions may temporarily alter visitor movement.', 'Christian Quarter §9 visitor guidance', 4),
  ('quiz-armenian-1', 'armenian-quarter', 'Which craft became a distinctive Armenian contribution to modern Jerusalem?', ARRAY['Hand-painted ceramics', 'Glass blowing', 'Soap making', 'Carpet weaving'], 0, 'Armenian artists arriving from 1919 developed a distinctive Jerusalem school of painted tile and pottery.', 'Armenian Quarter §2 and §5; Tel Aviv University ceramics history', 0),
  ('quiz-armenian-2', 'armenian-quarter', 'When did the Armenian Patriarchate establish its Jerusalem printing press?', ARRAY['1149', '1517', '1833', '1919'], 2, 'The printing press was founded in 1833 and became an important centre of Armenian-language publishing.', 'Armenian Quarter §2 and §5; St James Printing House research', 1),
  ('quiz-armenian-3', 'armenian-quarter', 'Much of the present Cathedral of St James dates to which period?', ARRAY['Twelfth century', 'Fourth century BCE', 'Sixteenth century', 'Twenty-first century'], 0, 'Much of the current cathedral took shape during the twelfth century while preserving earlier traditions and fabric.', 'Armenian Quarter §2 and §5', 2),
  ('quiz-armenian-4', 'armenian-quarter', 'What was the nineteenth-century building now used by the Armenian Museum originally built for?', ARRAY['A railway station', 'A pilgrim guesthouse', 'A military arsenal', 'A cotton market'], 1, 'It was built in the 1850s as a pilgrim guesthouse and later served community and refugee needs before becoming a museum.', 'Armenian Quarter §2; Associated Press museum report', 3),
  ('quiz-armenian-5', 'armenian-quarter', 'Which detail best helps identify the Armenian Quarter in the street?', ARRAY['Blue-and-white ceramic plaques and Armenian script', 'Neon skyscraper signs', 'Roman milestone columns only', 'Wooden suspension bridges'], 0, 'Armenian inscriptions, carved cross-stones and hand-painted ceramic plaques mark the community landscape.', 'Armenian Quarter §9', 4),
  ('quiz-maghariba-1', 'maghariba-quarter', 'With which wider region was the historic Maghariba Quarter connected?', ARRAY['The Maghreb', 'The Balkans', 'Anatolia', 'Mesopotamia'], 0, 'The quarter served communities and pilgrims connected with North Africa and the wider Maghreb.', 'Maghariba Quarter §1 and §3; Jerusalem Story', 0),
  ('quiz-maghariba-2', 'maghariba-quarter', 'Which year is associated with the Ayyubid endowment for Maghrebi residents and pilgrims?', ARRAY['1099', '1193', '1537', '1922'], 1, 'Historical accounts associate the charitable endowment with 1193 CE, soon after Salah al-Din restored Muslim rule.', 'Maghariba Quarter §2; PASSIA waqf study', 1),
  ('quiz-maghariba-3', 'maghariba-quarter', 'What happened to most of the quarter on 10–11 June 1967?', ARRAY['It became a museum', 'It was demolished and residents were displaced', 'It was enclosed by a new medieval wall', 'It was moved outside the Old City'], 1, 'Most of the built fabric was demolished and residents were displaced, leaving a radically changed urban setting.', 'Maghariba Quarter §2 and §5; UNESCO and PASSIA documentation', 2),
  ('quiz-maghariba-4', 'maghariba-quarter', 'What is essential for understanding the neighbourhood that no longer survives intact?', ARRAY['Only current satellite images', 'Historic photographs, waqf records and testimony', 'Legends without dates', 'A modern shopping map'], 1, 'Archival images, records and attributed family testimony help reconstruct the erased lanes and social fabric.', 'Maghariba Quarter §5, §7 and §9', 3),
  ('quiz-maghariba-5', 'maghariba-quarter', 'Which visitor method best reads this site responsibly?', ARRAY['Assume the present plaza is unchanged since antiquity', 'Compare the current space with a dated historical view', 'Ignore the surviving ascent', 'Photograph worshippers without asking'], 1, 'A dated comparison reveals the sharp change in scale and prevents the modern plaza from being mistaken for an unchanged ancient space.', 'Maghariba Quarter §9 visitor walkthrough', 4),
  ('quiz-sheikh-1', 'sheikh-jarrah', 'When did prominent Jerusalem families expand housing in Sheikh Jarrah outside the walls?', ARRAY['Late Ottoman era', 'Umayyad era', 'Crusader era', 'Early Byzantine era'], 0, 'Prominent Palestinian families built residences there during Jerusalem''s late nineteenth-century expansion.', 'Sheikh Jarrah §2', 0),
  ('quiz-sheikh-2', 'sheikh-jarrah', 'When was the Isaf al-Nashashibi house completed?', ARRAY['1833', '1922', '1956', '2001'], 1, 'The house was completed in 1922 and its design is attributed to architect Spiro Khouri.', 'Sheikh Jarrah §2 and §5; Jerusalem Quarterly', 1),
  ('quiz-sheikh-3', 'sheikh-jarrah', 'How many housing units do UN records note as completed in 1956?', ARRAY['12', '28', '54', '135'], 1, 'UN documentation records completion of 28 units connected with an arrangement for 28 refugee families.', 'Sheikh Jarrah §2 and §5; United Nations records', 2),
  ('quiz-sheikh-4', 'sheikh-jarrah', 'Which features express the neighbourhood''s villa heritage?', ARRAY['Stone arches, deep windows, tiled roofs and gardens', 'Glass towers and steel bridges', 'Mud-brick pyramids', 'Only underground rooms'], 0, 'Late Ottoman and Mandate-era villas use Jerusalem stone, arched openings, verandas, tiled roofs and planted gardens.', 'Sheikh Jarrah §9', 3),
  ('quiz-sheikh-5', 'sheikh-jarrah', 'Why must current property cases not be answered from the static heritage summary?', ARRAY['They are fictional', 'Legal outcomes and conditions can change', 'The neighbourhood has no residents', 'Historic architecture settles ownership'], 1, 'Current legal facts are time-sensitive and require up-to-date authoritative sources; architectural history cannot determine them.', 'Sheikh Jarrah §5 and §8 fact-guard note', 4),
  ('quiz-silwan-1', 'silwan', 'Which feature is central to Silwan''s historic landscape?', ARRAY['Ain Silwan', 'Bab al-Amud', 'Souq al-Qattanin', 'St James Cathedral'], 0, 'Ain Silwan connects water, settlement, cultivation and the neighbourhood''s living heritage.', 'Silwan §1 and §3', 0),
  ('quiz-silwan-2', 'silwan', 'Which medieval geographer described the spring and cultivated landscape below Jerusalem?', ARRAY['Herodotus', 'Al-Muqaddasi', 'Ibn Battuta', 'Marco Polo'], 1, 'The tenth-century geographer al-Muqaddasi described Jerusalem''s water and cultivated landscape.', 'Silwan §2; scholarly editions of al-Muqaddasi', 1),
  ('quiz-silwan-3', 'silwan', 'What do Silwan''s retaining walls and stacked roofs help visitors understand?', ARRAY['Its steep vertical terrain', 'A flat Roman parade ground', 'A coastal harbour', 'A planned industrial grid'], 0, 'Homes, paths and terraces respond to a steep valley-side landscape that is best read vertically.', 'Silwan §5 and §9', 2),
  ('quiz-silwan-4', 'silwan', 'Why should archaeology and present community life not be conflated?', ARRAY['Only one of them is real', 'They are different evidence layers sharing the same landscape', 'They occur in different countries', 'Archaeology has no dates'], 1, 'Ancient remains and contemporary Palestinian life overlap spatially but answer different historical and social questions.', 'Silwan §2, §5 and §8', 3),
  ('quiz-silwan-5', 'silwan', 'Which practical advice fits Silwan''s terrain?', ARRAY['Wear shoes with grip and avoid unmarked shortcuts', 'Expect level indoor corridors', 'Visit only by boat', 'Ignore current access conditions'], 0, 'The slopes and paths can be steep and uneven, so stable footwear and locally verified routes are important.', 'Silwan §9 visitor guidance', 4),
  ('quiz-tur-1', 'at-tur', 'What can the Mount of Olives viewpoint help visitors read?', ARRAY['The relation of walls, valleys and eastern ridge', 'The Mediterranean coastline', 'A coastal railway terminal', 'A modern airport runway'], 0, 'The panorama shows the physical relationship among the Old City walls, Kidron Valley and eastern ridge.', 'At-Tur §1 and §5', 0),
  ('quiz-tur-2', 'at-tur', 'Which valley separates the Mount of Olives from the Old City?', ARRAY['Jezreel Valley', 'Kidron Valley', 'Ayalon Valley', 'Jordan Valley'], 1, 'The Kidron Valley lies between the eastern Old City wall and the Mount of Olives ridge.', 'At-Tur §5; Custody of the Holy Land', 1),
  ('quiz-tur-3', 'at-tur', 'When was the present Church of All Nations consecrated?', ARRAY['1149', '1517', '1924', '1981'], 2, 'The present church at Gethsemane, designed by Antonio Barluzzi above earlier remains, was consecrated in 1924.', 'At-Tur §2 and §5; Custody of the Holy Land', 2),
  ('quiz-tur-4', 'at-tur', 'What creates the church''s solemn visual atmosphere?', ARRAY['A bright glass office interior', 'Dark blue vaults and subdued light', 'A rotating neon sign', 'An uncovered concrete roof'], 1, 'Its dark blue vaulting and controlled light contrast with the bright valley outside and support a devotional atmosphere.', 'At-Tur §5 and §9', 3),
  ('quiz-tur-5', 'at-tur', 'Which statement best respects the ridge''s identity?', ARRAY['It is only a pilgrimage viewpoint', 'It is both a sacred landscape and a living Palestinian neighbourhood', 'It contains no modern institutions', 'All tomb identifications are archaeologically certain'], 1, 'Homes, schools, hospitals and local commerce coexist with shrines, cemeteries and viewpoints.', 'At-Tur §1, §3 and §7', 4),
  ('quiz-amud-1', 'bab-al-amud', 'The visible monumental façade of Bab al-Amud belongs mainly to which period?', ARRAY['Ottoman', 'Roman', 'Byzantine', 'Mamluk'], 0, 'The present façade was built in 1537–1540 as part of Sultan Suleiman''s Ottoman walls, above earlier remains.', 'Bab al-Amud §2 and §5; Jerusalem Foundation', 0),
  ('quiz-amud-2', 'bab-al-amud', 'What is the likely origin of the Arabic name Bab al-Amud, “Gate of the Column”?', ARRAY['A modern lamp post', 'A column shown in the Roman plaza', 'A Mamluk minaret', 'A Crusader drawbridge'], 1, 'The sixth-century Madaba map shows a column in the inner Roman plaza, remembered in the Arabic name.', 'Bab al-Amud §2 and §3; University of Michigan gate record', 1),
  ('quiz-amud-3', 'bab-al-amud', 'During whose reign was the earlier Roman gate complex built?', ARRAY['Hadrian', 'Constantine', 'Salah al-Din', 'Suleiman'], 0, 'The Roman gate complex dates to the reign of Hadrian, when the city was refounded as Aelia Capitolina.', 'Bab al-Amud §2; University of Michigan gate record', 2),
  ('quiz-amud-4', 'bab-al-amud', 'Why does the gate passage turn instead of running straight through?', ARRAY['To create a defensive bent entrance', 'To follow an underground river', 'To make room for a railway', 'To face the Mediterranean'], 0, 'The bent-axis passage controls movement and prevents a direct approach through the fortification.', 'Bab al-Amud §5 and §9', 3),
  ('quiz-amud-5', 'bab-al-amud', 'Which market route continues south after entering the gate?', ARRAY['Souq al-Qattanin', 'Khan al-Zeit', 'Souq al-Bazaar', 'Karm al-Mufti'], 1, 'Khan al-Zeit carries the route into the Old City through a roofed commercial street.', 'Bab al-Amud §1, §4 and §9', 4);

COMMIT;
