import { ArtisanHighlight, LocationData, TourInterest } from "./types";

export interface JerusalemLocationData extends LocationData {
  categories: string[];
  interests: TourInterest[];
}

const sourcePage = (filename: string) =>
  `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(filename.replaceAll(" ", "_"))}`;

const commonsImage = (filename: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(filename)}?width=1600`;

export const locations: JerusalemLocationData[] = [
  {
    id: "muslim-quarter", name: "Muslim Quarter", arabicName: "حارة المسلمين", lat: 31.7806, lng: 35.2339,
    coverImage: "/images/jerusalem/muslim-quarter.jpg",
    summary: "The Old City’s largest quarter, shaped by Mamluk architecture, living markets and routes leading toward Al-Aqsa.",
    arabicSummary: "أكبر حارات البلدة القديمة، تنسج بين عمارتها المملوكية وأسواقها الحيّة والطرق المؤدية إلى المسجد الأقصى.",
    culturalImportance: "A dense living quarter where worship, commerce, schools, khans and family life meet.",
    arabicCulturalImportance: "حارة حيّة تتجاور فيها العبادة والتجارة والمدارس والخانات وذاكرة العائلات المقدسية.",
    historicalSummary: "Its lanes preserve major Mamluk and Ottoman urban layers. Bab Hutta, the Via Dolorosa and Souq al-Qattanin connect sacred space with daily city life.",
    arabicHistoricalSummary: "تحفظ أزقتها طبقات عمرانية مملوكية وعثمانية بارزة. ويربط باب حطة وطريق الآلام وسوق القطانين بين الفضاء المقدس والحياة اليومية للمدينة.",
    landmarks: ["Bab Hutta", "Via Dolorosa", "Souq al-Qattanin", "Mamluk madrasas"],
    arabicLandmarks: ["باب حطة", "طريق الآلام", "سوق القطانين", "المدارس المملوكية"],
    storyTitle: "Muslim Quarter: stone lanes and living markets", arabicStoryTitle: "حارة المسلمين: دروب الحجر والأسواق الحيّة",
    story: "Enter the Muslim Quarter through a network of stone lanes where homes, schools, markets and places of worship remain part of one living urban fabric. Bab Hutta, the Via Dolorosa and Souq al-Qattanin offer different ways to read the quarter: through community life, pilgrimage and Mamluk architecture. Follow the reviewed timeline and oral memories for what the archive supports; where evidence is incomplete, Hikayat AlQuds leaves the gap visible.",
    arabicStory: "ادخل حارة المسلمين عبر شبكة من الأزقة الحجرية التي تجمع البيوت والمدارس والأسواق وأماكن العبادة في نسيج عمراني حي. يتيح باب حطة وطريق الآلام وسوق القطانين قراءة الحارة من زوايا الحياة الاجتماعية والحج والعمارة المملوكية. اتبع الخط الزمني والذكريات الشفوية لمعرفة ما يسنده الأرشيف؛ وحين تكون الأدلة ناقصة تترك حكاية القدس الفجوة ظاهرة ولا تخمّن.",
    imageCredit: "Bekmaw", imageLicense: "CC BY-SA 4.0", imageSourceUrl: sourcePage("Souq al-Qattanin سوق القطانين القدس.jpg"),
    categories: ["حارة تاريخية", "معلم ديني", "سوق تراثي"], interests: ["history", "architecture", "religious", "food_markets", "oral_heritage"],
  },
  {
    id: "christian-quarter", name: "Christian Quarter", arabicName: "حارة النصارى", lat: 31.7784, lng: 35.2297,
    coverImage: "/images/jerusalem/christian-quarter.jpg",
    summary: "A quarter of churches, monasteries, hospices and markets centred on the Church of the Holy Sepulchre.",
    arabicSummary: "حارة الكنائس والأديرة والبيوت والأسواق التي تتمحور مساراتها حول كنيسة القيامة.",
    culturalImportance: "Christian communities and Jerusalemite families maintain a continuous religious and commercial presence here.",
    arabicCulturalImportance: "تحافظ الطوائف المسيحية والعائلات المقدسية على حضور ديني واجتماعي وتجاري متواصل في الحارة.",
    historicalSummary: "The quarter’s institutions reflect Byzantine, Crusader, Mamluk and Ottoman periods, while its lanes remain part of an active pilgrimage city.",
    arabicHistoricalSummary: "تعكس مؤسسات الحارة طبقات بيزنطية وصليبية ومملوكية وعثمانية، فيما تظل أزقتها جزءاً من مدينة حج نابضة بالحياة.",
    landmarks: ["Church of the Holy Sepulchre", "Latin Patriarchate", "Souq al-Bazaar"], arabicLandmarks: ["كنيسة القيامة", "دير اللاتين", "سوق البازار"],
    storyTitle: "Christian Quarter: bells, pilgrims and markets", arabicStoryTitle: "حارة النصارى: الأجراس والحج والأسواق",
    story: "The Christian Quarter is best understood on foot. Its lanes move between the Church of the Holy Sepulchre, monasteries, hospices and the small shops of the bazaar. The buildings record several historical periods, but this is not an open-air museum: worship, trade and family life continue here today.",
    arabicStory: "تُفهم حارة النصارى على مهل ومن خلال المشي. تنتقل أزقتها بين كنيسة القيامة والأديرة والخانات ومحال سوق البازار. تسجل مبانيها عصوراً تاريخية متعددة، لكنها ليست متحفاً مفتوحاً؛ فالعبادة والتجارة وحياة العائلات ما زالت مستمرة فيها اليوم.",
    imageCredit: "Deror avi", imageLicense: "CC BY-SA 3.0", imageSourceUrl: sourcePage("Christian Quarter IMG 0431.jpg"),
    categories: ["حارة تاريخية", "معلم ديني", "سوق تراثي"], interests: ["history", "architecture", "religious", "food_markets"],
  },
  {
    id: "armenian-quarter", name: "Armenian Quarter", arabicName: "حارة الأرمن", lat: 31.7747, lng: 35.2294,
    coverImage: "/images/jerusalem/armenian-quarter.jpg",
    summary: "A compact historic quarter known for St James Cathedral, Armenian institutions and Jerusalem’s distinctive ceramic tradition.",
    arabicSummary: "حارة تاريخية متماسكة تُعرف بكاتدرائية مار يعقوب ومؤسساتها الأرمنية وتقليد الخزف المقدسي المميّز.",
    culturalImportance: "The Armenian community has sustained worship, education, printing, craft and memory in Jerusalem for centuries.",
    arabicCulturalImportance: "حافظ المجتمع الأرمني عبر قرون على العبادة والتعليم والطباعة والحرفة والذاكرة في القدس.",
    historicalSummary: "The quarter grew around the monastery and Cathedral of St James; workshops later made hand-painted Armenian ceramics a signature Jerusalem craft.",
    arabicHistoricalSummary: "نمت الحارة حول دير وكاتدرائية مار يعقوب، ثم جعلت الورشات من الخزف الأرمني المرسوم يدوياً علامة مميزة للحرفة المقدسية.",
    landmarks: ["St James Cathedral", "Armenian Museum", "Armenian ceramic workshops"], arabicLandmarks: ["كاتدرائية مار يعقوب", "متحف الأرمن", "ورش الخزف الأرمني"],
    storyTitle: "Armenian Quarter: faith, print and painted clay", arabicStoryTitle: "حارة الأرمن: الإيمان والطباعة والخزف الملوّن",
    story: "The Armenian Quarter gathers a long communal history within a compact part of the Old City. St James Cathedral and the surrounding institutions anchor religious and educational life. In the modern period, Armenian workshops developed the hand-painted ceramics that many visitors now associate with Jerusalem.",
    arabicStory: "تجمع حارة الأرمن تاريخاً مجتمعياً طويلاً ضمن مساحة متماسكة من البلدة القديمة. ترتكز الحياة الدينية والتعليمية حول كاتدرائية مار يعقوب والمؤسسات المحيطة بها. وفي العصر الحديث طوّرت الورش الأرمنية تقليد الخزف المرسوم يدوياً الذي أصبح من العلامات البصرية المرتبطة بالقدس.",
    imageCredit: "John S Y Lee", imageLicense: "CC BY 2.0", imageSourceUrl: sourcePage("Entrance to the Cathedral of Saint James in the Armenian Quarter of Jerusalem.jpg"),
    categories: ["حارة تاريخية", "معلم ديني"], interests: ["history", "architecture", "religious", "oral_heritage"],
  },
  {
    id: "maghariba-quarter", name: "Maghariba Quarter", arabicName: "حي وحارة المغاربة", lat: 31.7755, lng: 35.2338,
    coverImage: "/images/jerusalem/maghariba-quarter.jpg",
    summary: "The remembered Maghrebi Quarter beside Bab al-Maghariba and al-Buraq Wall, documented as an urban community and endowed neighbourhood.",
    arabicSummary: "حارة مقدسية مستعادة من الذاكرة قرب باب المغاربة وحائط البراق، عُرفت مجتمعاً عمرانياً ووقفاً لخدمة القادمين من بلاد المغرب.",
    culturalImportance: "Its story keeps visible a displaced social fabric of homes, worship, endowments and North African ties.",
    arabicCulturalImportance: "تبقي حكايتها نسيجاً اجتماعياً مُهجّراً حاضراً في الذاكرة: بيوتاً وعبادةً وأوقافاً وصلاتٍ ببلاد المغرب.",
    historicalSummary: "The quarter is associated with an Ayyubid-era waqf for Maghrebi pilgrims. Most of its built fabric was demolished in June 1967; its memory remains central to Jerusalem’s urban history.",
    arabicHistoricalSummary: "ارتبطت الحارة بوقف من العصر الأيوبي لخدمة حجاج بلاد المغرب. هُدم معظم نسيجها العمراني في حزيران 1967، وبقيت ذاكرتها جزءاً مركزياً من تاريخ القدس الحضري.",
    landmarks: ["Bab al-Maghariba", "Al-Buraq Wall", "Site of the historic quarter"], arabicLandmarks: ["باب المغاربة", "حائط البراق", "موضع الحارة التاريخية"],
    storyTitle: "Maghariba Quarter: a neighbourhood held in memory", arabicStoryTitle: "حارة المغاربة: حيّ تحمله الذاكرة",
    story: "The Maghariba Quarter must be approached through documented memory as well as surviving space. It stood beside Bab al-Maghariba and al-Buraq Wall and was linked to an endowed community serving people from the Maghreb. Most of its buildings were demolished in June 1967, so historical photographs and testimonies are essential to understanding what is no longer visible.",
    arabicStory: "تُقرأ حارة المغاربة من خلال الذاكرة الموثقة بقدر ما تُقرأ من المكان القائم. كانت تقع قرب باب المغاربة وحائط البراق، وارتبطت بوقف يخدم القادمين من بلاد المغرب. هُدم معظم مبانيها في حزيران 1967، لذلك تصبح الصور التاريخية والشهادات ضرورية لفهم ما لم يعد ظاهراً اليوم.",
    imageCredit: "Ordnance Survey album, 1864", imageLicense: "Public domain", imageSourceUrl: sourcePage("19th century view of Jerusalem, including the Moroccan Quarter.jpg"),
    categories: ["حارة تاريخية", "معلم ديني"], interests: ["history", "architecture", "religious", "oral_heritage"],
  },
  {
    id: "sheikh-jarrah", name: "Sheikh Jarrah", arabicName: "حي الشيخ جراح", lat: 31.7917, lng: 35.2295,
    coverImage: "/images/jerusalem/sheikh-jarrah.jpg",
    summary: "A Jerusalem neighbourhood north of the Old City known for historic villas, cultural institutions and community steadfastness.",
    arabicSummary: "حي مقدسي شمال البلدة القديمة، يُعرف ببيوته التاريخية ومؤسساته الثقافية وصمود مجتمعه المحلي.",
    culturalImportance: "Family homes and cultural spaces make the neighbourhood a living record of modern Palestinian Jerusalem.",
    arabicCulturalImportance: "تجعل البيوت العائلية والفضاءات الثقافية من الحي سجلاً حياً للقدس الفلسطينية الحديثة.",
    historicalSummary: "The neighbourhood expanded outside the walls in the late Ottoman period. Its built heritage includes the Nashashibi palace and other villas set among gardens.",
    arabicHistoricalSummary: "توسّع الحي خارج الأسوار في أواخر العهد العثماني، ويضم تراثه العمراني قصر إسعاف النشاشيبي وبيوتاً وحدائق تاريخية أخرى.",
    landmarks: ["Isaf al-Nashashibi Palace", "Karm al-Mufti", "Jerusalemite family homes"], arabicLandmarks: ["قصر إسعاف النشاشيبي", "كرم المفتي", "بيوت العائلات المقدسية"],
    storyTitle: "Sheikh Jarrah: homes beyond the walls", arabicStoryTitle: "الشيخ جراح: بيوتٌ خارج الأسوار",
    story: "Sheikh Jarrah tells a modern Jerusalem story through houses, gardens and cultural institutions north of the Old City. The neighbourhood expanded during the late Ottoman period, and buildings such as the Nashashibi palace help explain that urban growth. Its heritage is also a living one, carried by families and community spaces.",
    arabicStory: "يروي الشيخ جراح حكاية القدس الحديثة من خلال البيوت والحدائق والمؤسسات الثقافية شمال البلدة القديمة. توسع الحي في أواخر العهد العثماني، وتساعد مبانٍ مثل قصر إسعاف النشاشيبي على قراءة ذلك النمو العمراني. وتراث الحي حيّ أيضاً، تحمله العائلات والفضاءات المجتمعية.",
    imageCredit: "Eman", imageLicense: "Public domain", imageSourceUrl: sourcePage("Kharufe house Sheikh Jarrah.JPG"),
    categories: ["حي مقدسي"], interests: ["history", "architecture", "oral_heritage"],
  },
  {
    id: "silwan", name: "Silwan", arabicName: "سلوان", lat: 31.7707, lng: 35.2368,
    coverImage: "/images/jerusalem/silwan.jpg",
    summary: "A hillside Jerusalem village south of the Old City, tied to the historic spring, terraced gardens and rich oral memory.",
    arabicSummary: "بلدة مقدسية على السفح الجنوبي للبلدة القديمة، ترتبط بعين سلوان والبساتين المدرّجة وذاكرة شفوية غنية.",
    culturalImportance: "Its landscape joins water, agriculture, family histories and the daily life of a long-established Jerusalemite community.",
    arabicCulturalImportance: "يجمع مشهدها بين الماء والزراعة وحكايات العائلات والحياة اليومية لمجتمع مقدسي عريق.",
    historicalSummary: "Silwan’s settlement history is closely connected with Ain Silwan and the Kidron Valley. Wadi Hilweh and the village’s gardens carry layered archaeological and oral histories.",
    arabicHistoricalSummary: "يرتبط تاريخ الاستقرار في سلوان بعين سلوان ووادي قدرون. ويحمل وادي حلوة وبساتين البلدة طبقات من التاريخ الأثري والذاكرة الشفوية.",
    landmarks: ["Ain Silwan", "Wadi Hilweh", "Silwan gardens"], arabicLandmarks: ["عين سلوان", "وادي حلوة", "بساتين سلوان"],
    storyTitle: "Silwan: spring, gardens and spoken memory", arabicStoryTitle: "سلوان: العين والبساتين والذاكرة المحكية",
    story: "Silwan descends along the slopes south of the Old City. Ain Silwan, the Kidron Valley and terraced gardens connect water and cultivation with generations of family memory. Archaeological interpretations and residents’ oral histories do not always answer the same questions, so Hikayat AlQuds identifies which kind of source supports each account.",
    arabicStory: "تمتد سلوان على السفوح جنوب البلدة القديمة. تربط عين سلوان ووادي قدرون والبساتين المدرّجة بين الماء والزراعة وذاكرة أجيال من العائلات. ولا تجيب القراءات الأثرية والذاكرة الشفوية للسكان دائماً عن الأسئلة نفسها؛ لذلك توضّح حكاية القدس نوع المصدر الذي يسند كل رواية.",
    imageCredit: "Ola Watad", imageLicense: "CC BY-SA 4.0", imageSourceUrl: sourcePage("قرية سلوان.jpg"),
    categories: ["حي مقدسي"], interests: ["history", "architecture", "oral_heritage"],
  },
  {
    id: "at-tur", name: "At-Tur & Mount of Olives", arabicName: "الطور وجبل الزيتون", lat: 31.7833, lng: 35.2442,
    coverImage: "/images/jerusalem/at-tur.jpg",
    summary: "The ridge east of the Old City offers a defining panorama and a landscape of shrines, cemeteries, churches and neighbourhood life.",
    arabicSummary: "يرسم السفح الشرقي للبلدة القديمة مشهداً بانورامياً تتجاور فيه المقامات والمقابر والكنائس وحياة حي الطور.",
    culturalImportance: "Sacred traditions and Jerusalemite community life share the same ridge and walking routes.",
    arabicCulturalImportance: "تتقاسم التقاليد الدينية وحياة المجتمع المقدسي السفح نفسه ومسارات المشي عليه.",
    historicalSummary: "The Mount of Olives has long served as a place of worship, burial and approach to Jerusalem. At-Tur developed as a living Palestinian neighbourhood across the ridge.",
    arabicHistoricalSummary: "كان جبل الزيتون عبر عصور طويلة مكاناً للعبادة والدفن وطريقاً للاقتراب من القدس، فيما تطور الطور حياً فلسطينياً حياً على امتداد السفح.",
    landmarks: ["Jerusalem panorama", "Tombs of the Prophets", "Gethsemane"], arabicLandmarks: ["المطلّة البانورامية على القدس", "مدافن الأنبياء", "الجثمانية"],
    storyTitle: "At-Tur and the Mount of Olives: reading the eastern ridge", arabicStoryTitle: "الطور وجبل الزيتون: قراءة السفح الشرقي",
    story: "From the Mount of Olives, Jerusalem’s walls, valleys and eastern ridge can be read in one view. Shrines, churches and cemeteries reflect several sacred traditions, while At-Tur remains a lived Palestinian neighbourhood. The viewpoint is therefore both a visual orientation stop and an encounter with everyday Jerusalem.",
    arabicStory: "من جبل الزيتون يمكن قراءة أسوار القدس وأوديتها وسفحها الشرقي في مشهد واحد. تعكس المقامات والكنائس والمقابر تقاليد دينية متعددة، فيما يبقى الطور حياً فلسطينياً مأهولاً. لذلك تُعد المطلّة محطة لفهم جغرافية المدينة ولقاءً مع حياتها اليومية في آن واحد.",
    imageCredit: "Daniel Case", imageLicense: "CC BY-SA 3.0", imageSourceUrl: sourcePage("Jerusalem panorama from Mount of Olives.jpg"),
    categories: ["حي مقدسي", "معلم ديني"], interests: ["history", "architecture", "religious"],
  },
  {
    id: "bab-al-amud", name: "Bab al-Amud", arabicName: "باب العامود ومحيطه", lat: 31.7816, lng: 35.2308,
    coverImage: "/images/jerusalem/bab-al-amud.jpg",
    summary: "Jerusalem’s monumental northern gate and a civic gathering place opening into Khan al-Zeit market.",
    arabicSummary: "بوابة القدس الشمالية المهيبة وساحتها الاجتماعية التي تفتح الطريق نحو سوق خان الزيت.",
    culturalImportance: "The steps and square are a meeting point, performance space and gateway to Old City trade and worship.",
    arabicCulturalImportance: "تمثّل الدرجات والساحة نقطة لقاء وفضاءً للأداء وبوابةً إلى تجارة البلدة القديمة وأماكن العبادة.",
    historicalSummary: "The present gate belongs to the Ottoman walls built under Sultan Suleiman in the 16th century, above earlier Roman-era remains.",
    arabicHistoricalSummary: "تعود الواجهة القائمة إلى الأسوار العثمانية التي بُنيت في عهد السلطان سليمان في القرن السادس عشر، فوق بقايا أقدم من العصر الروماني.",
    landmarks: ["Bab al-Amud", "Historic gate square", "Khan al-Zeit"], arabicLandmarks: ["باب العامود", "الساحة التاريخية", "سوق خان الزيت"],
    storyTitle: "Bab al-Amud: the city’s northern threshold", arabicStoryTitle: "باب العامود: عتبة القدس الشمالية",
    story: "Bab al-Amud is both a monument and a daily meeting place. Its present façade belongs to the sixteenth-century Ottoman walls, while remains beneath it point to earlier Roman layers. From the steps, the route continues through the gate toward Khan al-Zeit and the markets of the Old City.",
    arabicStory: "باب العامود معلم تاريخي ومكان لقاء يومي في الوقت نفسه. تنتمي واجهته القائمة إلى أسوار القرن السادس عشر العثمانية، فيما تشير البقايا تحتها إلى طبقات رومانية أقدم. ومن الدرج يمتد الطريق عبر البوابة نحو سوق خان الزيت وأسواق البلدة القديمة.",
    imageCredit: "Shlomo Roded / PikiWiki Israel", imageLicense: "CC BY 2.5", imageSourceUrl: sourcePage("125307 jerusalem - nablus gate square entrance PikiWiki Israel.jpg"),
    categories: ["معلم ديني", "سوق تراثي", "حارة تاريخية"], interests: ["history", "architecture", "food_markets", "oral_heritage"],
  },
];

export const locationById = (id: string) => locations.find((location) => location.id === id);

export const artisanHighlights: ArtisanHighlight[] = [
  {
    id: "cotton-market", locationId: "muslim-quarter", name: "Cotton Merchants’ Market", arabicName: "سوق القطانين", category: "market",
    description: "A Mamluk-era market axis of stone vaults and small Jerusalemite businesses leading toward Al-Aqsa.", arabicDescription: "محور سوق مملوكي ذو عقود حجرية ودكاكين مقدسية صغيرة يقود باتجاه المسجد الأقصى.",
    supportNote: "Buying directly from family-run stalls helps traditional Old City trade remain active.", arabicSupportNote: "الشراء المباشر من الدكاكين العائلية يساعد على استمرار تجارة البلدة القديمة التقليدية.",
    imageUrl: commonsImage("Souq al-Qattanin, East Jerusalem, (16221870911).jpg"), fallbackImageUrl: "/images/jerusalem/gallery/muslim-souq-2014.jpg", imageAlt: "Merchants and pedestrians beneath the stone vaults of Souq al-Qattanin", arabicImageAlt: "تجار ومارة تحت عقود سوق القطانين الحجرية",
    imageCredit: "yeowatzup", imageLicense: "CC BY 2.0", imageSourceUrl: sourcePage("Souq al-Qattanin, East Jerusalem, (16221870911).jpg"),
  },
  {
    id: "spice-market", locationId: "muslim-quarter", name: "Souq al-Attarin", arabicName: "سوق العطارين", category: "food",
    description: "Traditional spice, herb, coffee and pantry shops in the Old City souqs.", arabicDescription: "دكاكين تقليدية للتوابل والأعشاب والقهوة ومؤونة البيت في أسواق البلدة القديمة.",
    supportNote: "Choose locally packed spices and ask merchants about seasonal Jerusalem blends.", arabicSupportNote: "اختر التوابل المعبأة محلياً واسأل التجار عن الخلطات المقدسية الموسمية.",
    imageUrl: commonsImage("سوق العطارين البلده القديمه القدس.jpg"), fallbackImageUrl: "/images/jerusalem/artisans/souq-al-attarin-2012.jpg", imageAlt: "The signed stone entrance to Souq al-Attarin with merchants and shoppers", arabicImageAlt: "المدخل الحجري المسمّى لسوق العطارين مع التجار والمتسوقين",
    imageCredit: "Ahed Izhiman", imageLicense: "CC BY-SA 4.0", imageSourceUrl: sourcePage("سوق العطارين البلده القديمه القدس.jpg"),
  },
  {
    id: "kaak", locationId: "bab-al-amud", name: "Jerusalem Ka'ak Bakers", arabicName: "خبازو كعك القدس", category: "food",
    description: "Sesame-crusted Jerusalem bread sold around Bab al-Amud and the Old City approaches.", arabicDescription: "خبز القدس المغطى بالسمسم يُباع حول باب العامود وعلى مداخل البلدة القديمة.",
    supportNote: "A small purchase from neighbourhood bakeries supports a living food tradition.", arabicSupportNote: "شراء بسيط من مخابز الحي يساند تقليداً غذائياً ما زال حياً.",
    imageUrl: commonsImage("Baker in Jerusalem.JPG"), fallbackImageUrl: "/images/jerusalem/artisans/jerusalem-kaak-baker-2012.jpg", imageAlt: "A Jerusalem baker selling long sesame ka'ak from a street cart", arabicImageAlt: "خباز مقدسي يبيع كعك القدس الطويل المغطى بالسمسم من عربة",
    imageCredit: "Peter van der Sluijs", imageLicense: "CC BY-SA 3.0", imageSourceUrl: sourcePage("Baker in Jerusalem.JPG"),
  },
  {
    id: "khan-al-zait-sweets", locationId: "bab-al-amud", name: "Khan al-Zeit confectionery", arabicName: "حلويات سوق خان الزيت", category: "food",
    description: "Sweet shops and food counters continue the commercial route from Bab al-Amud into Khan al-Zeit.", arabicDescription: "تواصل محال الحلويات وواجهات الطعام المسار التجاري من باب العامود إلى سوق خان الزيت.",
    supportNote: "Choose a neighbourhood shop, ask what was prepared locally, and keep the busy passage clear.", arabicSupportNote: "اختر محلاً من محال السوق، واسأل عما أُعدّ محلياً، واترك الممر المزدحم مفتوحاً.",
    imageUrl: commonsImage("Suk Khan Az-Zait, 2019 (05).jpg"), fallbackImageUrl: "/images/jerusalem/gallery/bab-khan-zait-2019.jpg", imageAlt: "A confectionery counter in Jerusalem’s Khan al-Zeit market", arabicImageAlt: "واجهة محل حلويات في سوق خان الزيت بالقدس",
    imageCredit: "Bahnfrend", imageLicense: "CC BY-SA 4.0", imageSourceUrl: sourcePage("Suk Khan Az-Zait, 2019 (05).jpg"),
  },
  {
    id: "muristan-market", locationId: "christian-quarter", name: "Muristan market traders", arabicName: "تجار سوق المورستان", category: "market",
    description: "Small shops and cafés animate the Muristan’s historic courtyard network beside the Church of the Holy Sepulchre.", arabicDescription: "تنعش الدكاكين والمقاهي الصغيرة شبكة ساحات المورستان التاريخية بجوار كنيسة القيامة.",
    supportNote: "Choose locally owned shops and respect that opening hours may follow worship and family schedules.", arabicSupportNote: "اختر المحال المحلية واحترم اختلاف ساعات العمل بحسب العبادة وبرنامج العائلة.",
    imageUrl: commonsImage("Muristan Fountain Jerusalem (1).jpg"), fallbackImageUrl: "/images/jerusalem/gallery/christian-muristan-fountain-2013.jpg", imageAlt: "Shops and pedestrians around the Muristan market square in the Christian Quarter", arabicImageAlt: "المحال والمارة حول ساحة سوق المورستان في حارة النصارى",
    imageCredit: "Radosław Botev", imageLicense: "CC BY 3.0 PL", imageSourceUrl: sourcePage("Muristan Fountain Jerusalem (1).jpg"),
  },
  {
    id: "christian-bazaar-life", locationId: "christian-quarter", name: "Bazaar lanes and family shops", arabicName: "أزقة البازار والدكاكين العائلية", category: "market",
    description: "The quarter’s narrow market lanes connect pilgrimage routes with everyday groceries, textiles, cafés and small family businesses.", arabicDescription: "تربط أزقة السوق الضيقة بين طرق الحج والبقالات والمنسوجات والمقاهي والدكاكين العائلية اليومية.",
    supportNote: "Pause without blocking the lane, ask before photographing people, and favour locally owned shops.", arabicSupportNote: "توقف من دون إعاقة الزقاق، واستأذن قبل تصوير الناس، وفضّل المحال التي يديرها أهل القدس.",
    imageUrl: commonsImage("Christian Quarter IMG 8163.jpg"), fallbackImageUrl: "/images/jerusalem/christian-quarter.jpg", imageAlt: "Pedestrians and small shops in a Christian Quarter market lane", arabicImageAlt: "مارة ودكاكين صغيرة في أحد أزقة سوق حارة النصارى",
    imageCredit: "יוסף חטף סגול", imageLicense: "CC0 1.0", imageSourceUrl: sourcePage("Christian Quarter IMG 8163.jpg"),
  },
  {
    id: "armenian-ceramics", locationId: "armenian-quarter", name: "Armenian Ceramics", arabicName: "الخزف الأرمني المقدسي", category: "craft",
    description: "Hand-painted tiles and vessels developed into a distinctive Jerusalem craft in Armenian workshops.", arabicDescription: "بلاطات وأوانٍ مرسومة يدوياً تطورت في الورش الأرمنية إلى حرفة مقدسية مميزة.",
    supportNote: "Ask whether a piece was painted in the workshop; direct purchases sustain specialist skills.", arabicSupportNote: "اسأل إن كانت القطعة مرسومة داخل الورشة؛ فالشراء المباشر يحافظ على المهارات المتخصصة.",
    imageUrl: commonsImage("Armenian Ceramics P1130679.JPG"), fallbackImageUrl: "/images/jerusalem/gallery/armenian-ceramics-2012.jpg", imageAlt: "Hand-painted Armenian ceramic vessels and tiles in a Jerusalem workshop", arabicImageAlt: "أوانٍ وبلاطات خزفية أرمنية مرسومة يدوياً في ورشة مقدسية",
    imageCredit: "Deror Avi", imageLicense: "CC BY-SA 3.0", imageSourceUrl: sourcePage("Armenian Ceramics P1130679.JPG"),
  },
  {
    id: "armenian-workshop-front", locationId: "armenian-quarter", name: "Ceramic workshop fronts", arabicName: "واجهات ورش الخزف الأرمني", category: "craft",
    description: "Painted signs, tiled façades and workshop displays show how Armenian ceramic design became part of Jerusalem’s streetscape.", arabicDescription: "تكشف اللافتات المرسومة والواجهات المكسوة بالبلاط ومعروضات الورش كيف صار الخزف الأرمني جزءاً من مشهد القدس.",
    supportNote: "Look for work signed by the workshop and ask makers about their process before choosing a piece.", arabicSupportNote: "ابحث عن القطع الموقّعة باسم الورشة واسأل الصنّاع عن طريقة العمل قبل اختيار القطعة.",
    imageUrl: commonsImage("Armenian Quarter, Jerusalem 010.jpg"), fallbackImageUrl: "/images/jerusalem/gallery/armenian-quarter-detail-2014.jpg", imageAlt: "A ceramic workshop frontage in Jerusalem’s Armenian Quarter", arabicImageAlt: "واجهة ورشة خزف في حارة الأرمن بالقدس",
    imageCredit: "Pandukht", imageLicense: "CC BY-SA 4.0", imageSourceUrl: sourcePage("Armenian Quarter, Jerusalem 010.jpg"),
  },
  {
    id: "maghariba-memory", locationId: "maghariba-quarter", name: "Maghrebi waqf and family memory", arabicName: "ذاكرة الوقف والعائلات المغاربية", category: "market",
    description: "The former neighbourhood economy survives in waqf records, photographs and displaced families’ accounts rather than in an intact market street.", arabicDescription: "يبقى اقتصاد الحارة السابقة في سجلات الوقف والصور وشهادات العائلات المهجّرة، لا في سوق قائم بنسيجه الكامل.",
    supportNote: "Support carefully attributed community archives; do not turn displacement into an invented commercial story.", arabicSupportNote: "ساند الأرشيفات المجتمعية المنسوبة بوضوح، ولا تحوّل التهجير إلى حكاية تجارية مختلقة.",
    imageUrl: commonsImage("Mosque & Jews' wailing place LOC matpc.16909.tif"), fallbackImageUrl: "/images/jerusalem/maghariba-quarter.jpg", imageAlt: "A 1934–39 overview of Maghariba Quarter homes and courtyards beside al-Buraq Wall", arabicImageAlt: "مشهد بين 1934 و1939 لبيوت حارة المغاربة وأفنيتها بجوار حائط البراق",
    imageCredit: "Matson Collection / Library of Congress", imageLicense: "Public domain", imageSourceUrl: sourcePage("Mosque & Jews' wailing place LOC matpc.16909.tif"),
  },
  {
    id: "maghariba-lane-memory", locationId: "maghariba-quarter", name: "The lost residential lane", arabicName: "ذاكرة الزقاق السكني المفقود", category: "market",
    description: "An archival view preserves the close relationship between homes, passageways and al-Buraq Wall before the quarter’s demolition in June 1967.", arabicDescription: "تحفظ صورة أرشيفية علاقة البيوت بالممرات وحائط البراق قبل هدم الحارة في حزيران 1967.",
    supportNote: "Treat the site as a displaced neighbourhood, and support archives that keep residents’ names and urban memory visible.", arabicSupportNote: "تعامل مع الموضع بوصفه حياً مُهجّراً، وساند الأرشيفات التي تحفظ أسماء السكان وذاكرتهم العمرانية.",
    imageUrl: commonsImage("Mosque & Jews' wailing place LOC matpc.16910.jpg"), fallbackImageUrl: "/images/jerusalem/gallery/maghariba-quarter-early20c.jpg", imageAlt: "A historic residential lane of the Maghariba Quarter beside al-Buraq Wall", arabicImageAlt: "زقاق سكني تاريخي في حارة المغاربة بجوار حائط البراق",
    imageCredit: "Matson Collection / Library of Congress", imageLicense: "Public domain", imageSourceUrl: sourcePage("Mosque & Jews' wailing place LOC matpc.16910.jpg"),
  },
  {
    id: "sheikh-nashashibi", locationId: "sheikh-jarrah", name: "Isaf al-Nashashibi House", arabicName: "قصر إسعاف النشاشيبي", category: "market",
    description: "The 1922 stone villa is a documented landmark of Sheikh Jarrah’s Palestinian literary and cultural history.", arabicDescription: "الفيلا الحجرية المشيدة سنة 1922 معلم موثق من تاريخ الشيخ جراح الأدبي والثقافي الفلسطيني.",
    supportNote: "Attend only publicly announced cultural activities and respect the residential setting around the house.", arabicSupportNote: "احضر الفعاليات الثقافية المعلنة للعامة واحترم الطابع السكني المحيط بالقصر.",
    imageUrl: commonsImage("SheikhJarrakhVilaNashashibi105.JPG"), fallbackImageUrl: "/images/jerusalem/gallery/sheikh-nashashibi-2010.jpg", imageAlt: "The 1922 Isaf al-Nashashibi house and its Jerusalem-stone façade", arabicImageAlt: "قصر إسعاف النشاشيبي المشيّد عام 1922 وواجهته من الحجر المقدسي",
    imageCredit: "Eman", imageLicense: "Public domain", imageSourceUrl: sourcePage("SheikhJarrakhVilaNashashibi105.JPG"),
  },
  {
    id: "sheikh-gardens", locationId: "sheikh-jarrah", name: "Villa gardens and residential heritage", arabicName: "حدائق الفيلات والتراث السكني", category: "market",
    description: "Garden walls, mature shade trees and stone villas define an important part of Sheikh Jarrah’s residential character.", arabicDescription: "تشكل أسوار الحدائق وأشجار الظل العتيقة والفيلات الحجرية جانباً مهماً من طابع الشيخ جراح السكني.",
    supportNote: "View the streets respectfully without treating private homes and gardens as visitor attractions.", arabicSupportNote: "شاهد الشوارع باحترام من دون تحويل البيوت والحدائق الخاصة إلى مواقع سياحية.",
    imageUrl: commonsImage("Kharufe house Sheikh Jarrah.JPG"), fallbackImageUrl: "/images/jerusalem/sheikh-jarrah.jpg", imageAlt: "A stone villa and mature garden trees in Sheikh Jarrah", arabicImageAlt: "فيلا حجرية وأشجار حديقة عتيقة في حي الشيخ جراح",
    imageCredit: "Eman", imageLicense: "Public domain", imageSourceUrl: sourcePage("Kharufe house Sheikh Jarrah.JPG"),
  },
  {
    id: "silwan-gardens", locationId: "silwan", name: "Terrace and garden knowledge", arabicName: "معرفة المدرجات والبساتين", category: "food",
    description: "Oral histories of irrigated gardens, vegetables, olives and seasonal harvests preserve Silwan’s relationship with water and cultivation.", arabicDescription: "تحفظ روايات البساتين المروية والخضروات والزيتون والمواسم صلة سلوان بالماء والزراعة.",
    supportNote: "Use community-led visits and purchase local produce only where residents clearly offer it.", arabicSupportNote: "اختر الجولات التي يقودها المجتمع واشترِ المنتجات المحلية فقط حين يعرضها السكان بوضوح.",
    imageUrl: commonsImage("قرية سلوان.jpg"), fallbackImageUrl: "/images/jerusalem/silwan.jpg", imageAlt: "Silwan’s densely built hillside with remaining trees and cultivated terraces", arabicImageAlt: "سفح سلوان المبني بكثافة مع الأشجار والمدرجات الزراعية الباقية",
    imageCredit: "Ola Watad", imageLicense: "CC BY-SA 4.0", imageSourceUrl: sourcePage("قرية سلوان.jpg"),
  },
  {
    id: "silwan-stone", locationId: "silwan", name: "Stone terraces and building knowledge", arabicName: "خبرة الحجر والمدرجات", category: "craft",
    description: "Retaining walls, steps and repaired terraces show practical knowledge adapted to Silwan’s steep slopes.", arabicDescription: "تكشف الجدران الاستنادية والدرجات والمدرجات المرممة خبرة عملية متكيفة مع سفوح سلوان الشديدة.",
    supportNote: "Respect active work sites and favour resident-led interpretation over unverified commercial tours.", arabicSupportNote: "احترم مواقع العمل النشطة وفضّل التفسير الذي يقوده السكان على الجولات التجارية غير الموثقة.",
    imageUrl: commonsImage("VIEW OF SILWAN VILLAGE IN THE KIDRON VALLEY IN JERUSALEM. צילום כללי של כפר השילוח (סילואן), בנחל קידרון בירושלים. (cropped).jpg"), fallbackImageUrl: "/images/jerusalem/gallery/silwan-1920.jpg", imageAlt: "Silwan’s stone houses and retaining terraces photographed in 1920", arabicImageAlt: "بيوت سلوان الحجرية ومدرجاتها الاستنادية في صورة من عام 1920",
    imageCredit: "LARSSON", imageLicense: "Public domain", imageSourceUrl: sourcePage("VIEW OF SILWAN VILLAGE IN THE KIDRON VALLEY IN JERUSALEM. צילום כללי של כפר השילוח (סילואן), בנחל קידרון בירושלים. (cropped).jpg"),
  },
  {
    id: "tur-olive", locationId: "at-tur", name: "Olive landscape and local hospitality", arabicName: "مشهد الزيتون والضيافة المحلية", category: "food",
    description: "Olive trees, family food traditions and small neighbourhood cafés connect the ridge’s sacred landscape with everyday At-Tur.", arabicDescription: "تصل أشجار الزيتون وتقاليد الطعام العائلية ومقاهي الحي الصغيرة بين المشهد المقدس والحياة اليومية في الطور.",
    supportNote: "Buy from clearly local vendors and do not repeat unsupported claims about the exact age of individual trees.", arabicSupportNote: "اشترِ من الباعة المحليين، ولا تكرر ادعاءات غير موثقة عن العمر الدقيق لكل شجرة.",
    imageUrl: commonsImage("Garden of Gethsemane Olive Trees (25595685200).jpg"), fallbackImageUrl: "/images/jerusalem/gallery/at-tur-gethsemane-olives-2016.jpg", imageAlt: "Gnarled living olive trees in Gethsemane at the foot of At-Tur", arabicImageAlt: "أشجار زيتون معمّرة حيّة في الجثمانية عند سفح الطور",
    imageCredit: "Konrad Summers", imageLicense: "CC BY-SA 2.0", imageSourceUrl: sourcePage("Garden of Gethsemane Olive Trees (25595685200).jpg"),
  },
  {
    id: "tur-community", locationId: "at-tur", name: "Neighbourhood services around pilgrimage routes", arabicName: "خدمات الحي حول طرق الحج", category: "market",
    description: "Groceries, cafés and everyday services continue beside hospitals, schools, churches and pilgrimage stops.", arabicDescription: "تستمر البقالات والمقاهي والخدمات اليومية إلى جوار المستشفيات والمدارس والكنائس ومحطات الحج.",
    supportNote: "Spend locally while keeping pavements and entrances clear for residents, patients and students.", arabicSupportNote: "أنفق محلياً مع إبقاء الأرصفة والمداخل مفتوحة للسكان والمرضى والطلبة.",
    imageUrl: commonsImage("A-Tur1142.JPG"), fallbackImageUrl: "/images/jerusalem/artisans/at-tur-neighbourhood-2017.jpg", imageAlt: "A grocery and small food businesses on an everyday street in At-Tur", arabicImageAlt: "بقالة ومحال طعام صغيرة في شارع يومي بحي الطور",
    imageCredit: "Yaakov", imageLicense: "CC BY-SA 4.0", imageSourceUrl: sourcePage("A-Tur1142.JPG"),
  },
];

export const voiceOptions = [
  { name: "ليلى", voiceName: "Kore", gender: "Female" as const, description: "صوت دافئ وواضح للسرد العربي." },
  { name: "سامي", voiceName: "Charon", gender: "Male" as const, description: "صوت هادئ لجولة تاريخية." },
];
