package ps.hikayatalquds.data.asset

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The shape of the JSON in `assets/content/`.
 *
 * These files are generated by `android/tools/export-assets.ts` from the same
 * reviewed sources the website and the API read, so this is not a second copy
 * of the content - it is the same content in a form the app can open with no
 * network and no database server.
 */

@Serializable
data class BundledCitation(
    val title: String,
    val arabicTitle: String = "",
    val publisher: String = "",
    val arabicPublisher: String = "",
    val url: String = "",
)

@Serializable
data class BundledLocation(
    val id: String,
    val name: String,
    val arabicName: String = "",
    val city: String = "Jerusalem",
    val country: String = "Palestine",
    val latitude: Double,
    val longitude: Double,
    val description: String = "",
    val arabicDescription: String = "",
    val culturalImportance: String = "",
    val arabicCulturalImportance: String = "",
    val historicalSummary: String = "",
    val arabicHistoricalSummary: String = "",
    val landmarks: List<String> = emptyList(),
    val arabicLandmarks: List<String> = emptyList(),
    val storyTitle: String = "",
    val arabicStoryTitle: String = "",
    val story: String = "",
    val arabicStory: String = "",
    val walkthrough: String = "",
    val arabicWalkthrough: String = "",
    val coverImage: String? = null,
    val coverImageCredit: String? = null,
    val coverImageLicense: String? = null,
    val coverImageSourceUrl: String? = null,
    val contentFile: String? = null,
    val categories: List<String> = emptyList(),
    val interests: List<String> = emptyList(),
    val isPublished: Boolean = true,
    val citations: List<BundledCitation> = emptyList(),
)

@Serializable
data class BundledStory(
    val id: String,
    val locationId: String,
    val title: String,
    val summary: String = "",
    val simplifiedStory: String = "",
    val audience: String = "general",
    val language: String = "en",
    val tone: String = "storytelling",
    val source: String? = null,
    val isAiGenerated: Boolean = false,
    val uncertaintyNotes: List<String> = emptyList(),
    val status: String = "published",
    val arabicTitle: String = "",
    val arabicSummary: String = "",
    val arabicSimplifiedStory: String = "",
)

@Serializable
data class BundledTimelineEvent(
    val id: String,
    val locationId: String,
    val periodLabel: String,
    val description: String,
    val sortYear: Int = 0,
    val sortOrder: Int = 0,
    val isTradition: Boolean = false,
    val sourceFile: String? = null,
    val arabicPeriodLabel: String = "",
    val arabicDescription: String = "",
)

@Serializable
data class BundledMedia(
    val id: String,
    val locationId: String,
    val type: String = "image",
    val subject: String = "",
    val arabicSubject: String = "",
    val description: String = "",
    val arabicDescription: String = "",
    val era: String = "modern",
    val pairRole: String? = null,
    /** Relative path inside `assets/`, present when the photograph ships offline. */
    val assetPath: String? = null,
    val remoteUrl: String? = null,
    val remoteThumbUrl: String? = null,
    val credit: String? = null,
    val license: String? = null,
    val licenseUrl: String? = null,
    val capturedAt: String? = null,
    val sourceUrl: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    val sortOrder: Int = 0,
)

@Serializable
data class BundledQuizQuestion(
    val id: String,
    val locationId: String,
    val question: String,
    val options: List<String> = emptyList(),
    val answerIndex: Int = 0,
    val explanation: String = "",
    val sourceNote: String = "",
    val sortOrder: Int = 0,
    val arabicQuestion: String = "",
    val arabicOptions: List<String> = emptyList(),
    val arabicExplanation: String = "",
    val arabicSourceNote: String = "",
)

@Serializable
data class BundledMemory(
    val id: String,
    val referenceCode: String? = null,
    val locationId: String,
    val title: String,
    val content: String,
    val contributorName: String? = null,
    val status: String = "approved",
    val submittedAt: String = "",
)

@Serializable
data class BundledArtisan(
    val id: String,
    val locationId: String,
    val name: String,
    val arabicName: String = "",
    val category: String = "craft",
    val description: String = "",
    val arabicDescription: String = "",
    val supportNote: String = "",
    val arabicSupportNote: String = "",
    val locationNote: String = "",
    val arabicLocationNote: String = "",
    @SerialName("imageUrl") val assetPath: String? = null,
    val fallbackImageUrl: String? = null,
    val remoteImageUrl: String? = null,
    val imageAlt: String = "",
    val arabicImageAlt: String = "",
    val imageCredit: String? = null,
    val imageLicense: String? = null,
    val imageSourceUrl: String? = null,
)

@Serializable
data class BundledVoice(
    val name: String,
    val voiceName: String,
    val gender: String = "Female",
    val description: String = "",
)
